INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('72163','P.O. Box 986, 3204 Duis St.','1367','Amstelveen','nibh. Phasellus nulla. Integer vulputate, risus a');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('37760','P.O. Box 466, 4418 Senectus Avenue','401','Walsall','penatibus et magnis dis parturient montes,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('U3P 3A3','6394 Luctus Street','1213','Baltasound','gravida sagittis. Duis gravida. Praesent eu nulla at sem');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V8F 3G8','9385 A St.','1312','Cortil-Noirmont','dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P1V 4G7','P.O. Box 384, 6225 Mollis. St.','1461','Victoria','risus a ultricies adipiscing, enim mi tempor lorem,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C2P 4Y5','P.O. Box 196, 8460 Gravida Av.','1305','Port Glasgow','libero.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('17156','8979 Nascetur Rd.','75','Jauchelette','In mi pede, nonummy ut, molestie in,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('25249','P.O. Box 982, 5813 Neque Road','966','Saint-Marc','porta elit, a feugiat tellus lorem eu');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('83306','P.O. Box 250, 971 Posuere Rd.','769','Oyen','enim. Nunc ut erat. Sed nunc est, mollis non,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('51010','P.O. Box 292, 687 Enim Avenue','985','Salt Spring Island','eget tincidunt dui augue eu tellus. Phasellus elit pede,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('M8W 7Y9','P.O. Box 607, 2420 Adipiscing. Street','1282','Merthyr Tydfil','libero. Donec consectetuer mauris id');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('R9R 5N2','Ap #692-8265 Nec, Street','170','Ottignies-Louvain-la-Neuve','Cras interdum. Nunc sollicitudin commodo');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('33765','242-9261 Libero Rd.','871','Skegness','sit amet, risus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('78837','P.O. Box 989, 6993 Sit Avenue','1381','Cranbrook','tristique aliquet.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('34773','Ap #619-5821 Turpis. Rd.','637','Ophain-Bois-Seigneur-Isaac','consequat auctor, nunc');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F6L 4R4','6886 Molestie St.','800','Villers-la-Ville','ut, sem. Nulla interdum. Curabitur dictum. Phasellus in');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('01454','5714 A St.','104','Stewart','Vivamus nibh dolor, nonummy ac, feugiat non,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('30069','3236 Quam. Rd.','1460','Columbus','ut, molestie in, tempus eu, ligula. Aenean euismod');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G6M 1T7','P.O. Box 348, 9116 Laoreet Av.','1115','Wabamun','eros non enim commodo hendrerit. Donec porttitor tellus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P3O 4Z6','8265 Justo St.','954','Bersillies-lAbbaye','Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('D5S 9W3','2803 Ante. Rd.','805','Esneux','parturient montes, nascetur ridiculus mus. Proin vel');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('O5D 2T0','5273 Imperdiet St.','1237','Sedgewick','sagittis. Nullam vitae diam. Proin dolor. Nulla semper');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('81504','Ap #429-4381 Risus, Ave','910','Alert Bay','dictum. Phasellus in felis. Nulla tempor augue ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('41914','3615 Ac Avenue','1500','Herk-de-Stad','et, magna. Praesent interdum ligula eu enim. Etiam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('28551','Ap #261-2579 Dui, Ave','382','Oklahoma City','amet, consectetuer adipiscing');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('S3D 8L8','P.O. Box 148, 2164 Interdum Rd.','1086','Villers-lez-Heest','tellus id nunc interdum feugiat.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('79151','2187 Malesuada Road','919','Booischot','orci quis lectus. Nullam suscipit,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G8Z 2G0','Ap #686-6218 Parturient Rd.','710','Thunder Bay','per inceptos hymenaeos. Mauris ut');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('55954','Ap #962-3367 Adipiscing Rd.','1069','Knokke-Heist','Cras lorem lorem, luctus ut, pellentesque eget,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G2K 2J4','7806 Sagittis Ave','751','Sherborne','Donec nibh. Quisque nonummy ipsum non');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('43873','6331 Aliquet St.','827','Paulatuk','Fusce aliquam,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('91530','617-9318 Pharetra, Road','1116','Calder','molestie tellus. Aenean egestas');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('85058','286 Amet Rd.','407','Shipshaw','eu, accumsan sed, facilisis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('28623','P.O. Box 223, 124 Dignissim. Ave','1059','Pittsburgh','auctor ullamcorper, nisl arcu');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('30605','840-7160 A Av.','1037','Hamme','gravida. Praesent eu nulla at sem');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('U2J 6Y3','470 Vitae St.','1193','Lathuy','Phasellus elit pede, malesuada vel, venenatis vel,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C7A 4G6','P.O. Box 461, 688 Semper Street','980','Penticton','nascetur ridiculus mus. Donec dignissim magna');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('H5A 6D3','Ap #147-1740 Ut Rd.','669','Loverval','eu enim. Etiam imperdiet dictum magna.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('J3J 9B1','P.O. Box 758, 2761 Nec St.','793','Gijzegem','lorem, auctor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('63224','Ap #693-8296 Pharetra. Street','1133','Grimbergen','dictum placerat, augue. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('75484','Ap #862-2250 Dolor Road','1053','Maryborough','Nam nulla magna,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('28888','Ap #177-7683 Vestibulum Ave','1101','Dorval','a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W5H 4X0','120 Curabitur Rd.','918','Lathuy','varius orci, in consequat enim diam vel arcu. Curabitur ut');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('02184','718-5521 Etiam Rd.','368','Forfar','nec, cursus a, enim. Suspendisse aliquet, sem ut');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('51630','P.O. Box 639, 9794 Ligula Avenue','731','Donstiennes','dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W6U 3X2','P.O. Box 848, 751 Auctor Avenue','123','Avernas-le-Bauduin','metus sit amet');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('69216','194-4754 Augue Street','1460','Boneffe','Pellentesque ut ipsum ac mi eleifend egestas. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Y4H 2L9','P.O. Box 523, 3458 Tristique St.','720','Great Yarmouth','molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F7B 8O1','Ap #985-6488 Mi Rd.','1436','Hamme','odio. Nam interdum enim');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('57339','P.O. Box 564, 5612 Velit St.','580','Dollard-des-Ormeaux','diam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I7Q 9E8','P.O. Box 743, 4193 Nunc St.','317','Southend','laoreet posuere, enim nisl');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('38246','942-1031 Magnis St.','900','Sainte-Marie-sur-Semois','eu, ultrices sit amet, risus. Donec nibh');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('25227','993-2333 Dolor Rd.','1262','Kalgoorlie-Boulder','aliquet. Phasellus fermentum convallis ligula. Donec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('77022','4189 Ultrices. Rd.','1221','Gibsons','luctus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('O9F 7M6','5268 Nunc St.','358','Montbliart','Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('15610','Ap #801-8302 Nunc Street','1500','Ohain','sem. Pellentesque ut ipsum ac mi eleifend egestas.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W6J 1G1','P.O. Box 685, 3486 Mauris Av.','391','Guirsch','sem, vitae aliquam eros turpis non');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z5G 9U1','P.O. Box 542, 9633 Enim. St.','473','Fredericton','libero at auctor ullamcorper, nisl arcu iaculis enim,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('16875','Ap #792-2523 Sed Rd.','739','Tuscaloosa','mi lacinia mattis. Integer eu lacus. Quisque');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('80854','500-6029 Amet Av.','1057','Zuienkerke','nibh enim, gravida sit amet, dapibus id,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('R6O 4P0','696-7400 Imperdiet Avenue','253','Sint-Gillis','Quisque imperdiet, erat nonummy');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q3K 3D3','Ap #155-1386 Vitae, Street','1269','Newtown','pharetra. Quisque ac libero nec ligula consectetuer rhoncus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('02051','Ap #458-2560 Lacinia Avenue','343','Spalbeek','sem magna nec quam. Curabitur');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('89993','Ap #147-8371 Nullam Rd.','180','Kapelle-op-den-Bos','Morbi vehicula. Pellentesque tincidunt tempus risus. Donec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('R7A 2Q1','P.O. Box 465, 8482 Purus Rd.','418','Montgomery','ut, pharetra sed,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('74011','5149 Hendrerit. Avenue','482','Ligney','sit amet diam eu');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('96669','8069 Enim, Avenue','766','Aurora','egestas. Fusce aliquet magna a neque. Nullam ut nisi a');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('91082','P.O. Box 965, 7350 Elit. St.','1297','Sart-Eustache','eget, dictum placerat,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z6L 7B0','P.O. Box 816, 1361 Feugiat. St.','806','Nerem','nunc. Quisque ornare tortor at risus. Nunc ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('U3G 8G3','7107 Nulla Ave','463','Marystown','purus. Maecenas');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('19929','Ap #643-8162 Dolor. Av.','327','Milestone','parturient montes, nascetur ridiculus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X1U 5D8','265-7612 Cum St.','29','Vlezenbeek','commodo auctor velit. Aliquam nisl. Nulla');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q3T 1O4','206-1287 Arcu. St.','39','Bornival','Mauris molestie pharetra nibh. Aliquam ornare,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('28477','239-1537 Donec Av.','155','Onze-Lieve-Vrouw-Lombeek','imperdiet ornare. In faucibus. Morbi');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('R7B 6Q3','265-9463 Et St.','196','Kenosha','diam nunc, ullamcorper eu,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F5V 3G6','382-7252 Morbi Rd.','712','Idaho Falls','dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('06595','771-8379 In Street','1259','Galmaarden','Sed eget');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('37637','404-1921 Malesuada St.','673','Cessnock','massa. Vestibulum accumsan neque et nunc.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G9E 6F8','903-5615 Ante. Road','773','Vezin','tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I3G 6H0','125-9278 Tincidunt Rd.','1347','Kallo','nunc risus varius');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('61875','736-9579 Nisl. Rd.','710','Bourlers','sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V5L 5G3','6888 Eu Av.','1257','Port Moody','tincidunt dui augue eu tellus. Phasellus elit pede,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('T9D 8E8','P.O. Box 597, 4482 Turpis St.','885','Pictou','consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('B4V 8V0','4050 Lacinia Avenue','19','Tielen','nostra, per inceptos hymenaeos. Mauris ut quam vel sapien');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('72058','Ap #558-333 Maecenas Av.','918','Poucet','Vivamus nibh dolor, nonummy');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('07523','Ap #413-2185 Adipiscing St.','1066','Ottignies-Louvain-la-Neuve','neque. In ornare sagittis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('90351','355-492 Interdum Rd.','45','Diegem','orci lacus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z5I 2W1','900 Rutrum Avenue','1000','Deurne','Duis risus odio, auctor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('88769','Ap #105-908 Primis Avenue','359','Hines Creek','In ornare sagittis felis.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('97132','Ap #624-8953 Cursus Av.','773','Stratford','libero nec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('22359','P.O. Box 355, 4597 Ligula. Avenue','358','Beverlo','Morbi metus. Vivamus euismod urna.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('89267','455-7947 Cras Street','421','Walsall','neque pellentesque massa lobortis ultrices. Vivamus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('12493','P.O. Box 439, 6914 Non, St.','974','Inuvik','molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('69058','6463 Massa. Road','718','Hulshout','tellus eu');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('J7K 1Y8','P.O. Box 871, 5840 A Ave','636','Fairbanks','molestie orci tincidunt adipiscing. Mauris');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F4A 7O1','546-5685 Interdum. St.','485','Osgoode','mollis. Duis sit amet diam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q9T 2M8','P.O. Box 324, 1734 Risus. Rd.','202','Kallo','non enim commodo hendrerit.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('00044','Ap #795-1242 Ipsum. Av.','385','Saint-Pierre','Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I6B 2T6','Ap #289-5526 Proin Road','118','Springfield','enim nec tempus scelerisque, lorem ipsum sodales purus,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W8B 5P0','282-1026 Nunc Street','429','Paulatuk','eget, dictum placerat, augue. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('98714','1368 Dui Street','639','San Antonio','Fusce aliquet magna a neque. Nullam ut nisi a');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z8S 5A3','5985 Aenean Ave','1315','Virginia Beach','dui. Suspendisse ac metus vitae velit egestas lacinia.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('01808','6949 Vitae Rd.','1163','Baileux','nec, diam. Duis mi enim, condimentum eget,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('M8W 3C8','2267 Suscipit Rd.','1076','Saltcoats','feugiat tellus lorem eu metus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G3S 3G8','830-3630 Elit, Rd.','175','Dandenong','dapibus gravida. Aliquam tincidunt, nunc');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('B3N 3I4','P.O. Box 259, 1038 Diam. Rd.','452','Holywell','magnis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q2E 5Q7','Ap #162-7392 Arcu St.','684','Chattanooga','Mauris non dui nec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z8A 3U0','661-1438 Tempus Rd.','570','Muiden','neque non quam. Pellentesque habitant morbi tristique');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('E4J 7A6','Ap #236-587 Tincidunt St.','689','Alphen aan den Rijn','eleifend egestas.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('M8Q 2B1','Ap #987-3159 Sed Rd.','879','Moncton','erat nonummy ultricies ornare, elit elit fermentum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P1D 6Z4','9928 Neque Av.','614','Lairg','velit justo nec ante. Maecenas mi felis,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('71537','5541 Diam Ave','701','Aurora','ut, pharetra sed, hendrerit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('U9H 1P4','267-1021 Porttitor Ave','1188','Jackson','erat volutpat. Nulla dignissim. Maecenas ornare egestas');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('32656','625-6168 Risus Ave','1065','Newark','tempus risus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('92852','9245 Nibh. Rd.','117','Mussy-la-Ville','sed, hendrerit a, arcu.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('06130','773-991 At Rd.','974','Ougr?e','Proin vel nisl. Quisque fringilla euismod enim.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('58399','218-6535 Odio. Avenue','584','South Perth','In ornare sagittis felis. Donec tempor, est ac mattis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('20930','1434 Sem. St.','1397','Sint-Ulriks-Kapelle','mollis. Phasellus libero');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L3X 7S1','2708 Dis St.','236','Deventer','libero nec ligula consectetuer rhoncus. Nullam velit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('39279','Ap #523-3231 Ligula. St.','1016','Nederhasselt','et malesuada');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('45465','4471 Dolor, Rd.','972','Kapuskasing','Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('62132','2364 Quis St.','1469','Portsoy','cursus et, eros. Proin ultrices. Duis volutpat');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A8A 6J8','Ap #447-345 Lorem, Rd.','1317','Trazegnies','Donec tempor, est ac mattis semper, dui');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('45906','3538 Ornare. Avenue','1059','Bothey','risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('61849','P.O. Box 896, 8115 Morbi Rd.','44','Chelsea','sagittis placerat.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('E5P 3Q9','P.O. Box 691, 1674 Vel St.','392','Springdale','ac mattis velit justo nec ante.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('54739','193-2753 Rhoncus. Rd.','1436','Alix','pretium neque. Morbi quis urna. Nunc quis arcu vel');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z1A 1O9','2174 Elit, Rd.','146','Bergen op Zoom','in molestie tortor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z2H 5Q9','Ap #890-2017 Integer St.','272','Carlisle','Nunc mauris elit, dictum eu, eleifend');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('71326','539-9803 Justo Avenue','584','Vucht','mauris ipsum porta');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('T4N 3F7','Ap #640-2817 Nisi Av.','206','Herstal','Mauris quis turpis vitae');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('N1E 4F8','365-2454 Ullamcorper, St.','1416','Invergordon','aliquam, enim');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('08642','P.O. Box 104, 8178 At Street','528','Austin','dignissim. Maecenas ornare egestas');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('49245','790-7658 Ac, Ave','1058','Bodmin','tellus non magna. Nam ligula elit, pretium');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('43159','P.O. Box 803, 5940 Ullamcorper Rd.','1200','Bressoux','tellus, imperdiet non, vestibulum nec, euismod');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W2F 8C4','3970 Tellus Rd.','294','Columbus','Fusce mi lorem, vehicula et, rutrum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('70463','P.O. Box 534, 8689 Ut Road','547','Knoxville','Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('16439','Ap #585-5906 Risus. Ave','598','Ligny','Curabitur consequat, lectus sit amet luctus vulputate, nisi sem');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A4P 7C1','Ap #550-2361 Elit, St.','974','Iqaluit','vitae purus gravida');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('67062','2016 Molestie Rd.','767','Lakeland County','lobortis, nisi nibh lacinia orci, consectetuer euismod');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W5G 9B7','195-8156 In Road','395','Scunthorpe','a felis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('25463','612-6656 Aptent Street','1245','Linton','placerat. Cras dictum ultricies ligula. Nullam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W8V 7I6','P.O. Box 539, 3066 Molestie Rd.','1184','Banff','orci, consectetuer euismod est');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I4H 2U4','7454 Magna. Street','118','Poole','et magnis dis parturient montes, nascetur ridiculus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C3P 3R1','8851 Amet Rd.','349','Merdorp','odio. Aliquam vulputate ullamcorper magna.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('20549','164-4310 Magnis Rd.','698','Fort Smith','velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('19542','932-5138 Ultrices, Avenue','1244','Colchester','auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('90460','P.O. Box 811, 155 Amet Ave','371','Canning','dis parturient montes, nascetur ridiculus mus. Proin vel arcu');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L9D 8T7','Ap #648-4267 Augue Street','572','Ferri?res','Cras sed leo. Cras vehicula aliquet libero. Integer');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('J6Q 1Z7','P.O. Box 372, 8278 Vitae, Rd.','651','Bertr?e','non dui nec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('76790','Ap #709-2901 Enim. Road','1472','Ramsey','faucibus orci luctus et ultrices posuere cubilia Curae;');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('22757','648-8628 Venenatis Av.','663','Arviat','nibh lacinia');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('79842','290-9271 Tellus. Rd.','852','Forfar','semper pretium neque. Morbi quis urna. Nunc quis arcu vel');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('D1G 7B0','Ap #383-1283 Mollis. Ave','967','Assen','mauris');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('S7K 3U6','P.O. Box 109, 9597 Phasellus Rd.','793','Sint-Denijs-Westrem','sem ut cursus luctus, ipsum leo elementum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('26322','Ap #203-7906 Tincidunt Avenue','214','Uitbergen','sem ut cursus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V1L 1M9','8813 Velit Rd.','329','Moncton','eu, placerat eget, venenatis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('78890','P.O. Box 865, 712 Curabitur St.','149','Greenwich','quis accumsan convallis, ante lectus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I2D 3X1','356-1313 Pharetra Ave','971','Caledon','nunc id');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('52848','806-3956 Consequat, Road','1125','Ragnies','gravida sagittis. Duis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P9R 1Z4','756-1761 Lobortis Rd.','1346','Villers-le-Peuplier','pede et risus. Quisque libero lacus,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I4R 5D3','P.O. Box 433, 9095 Donec Road','510','Moose Jaw','neque. In ornare sagittis felis. Donec tempor, est');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('S8V 2R6','285-4819 Ut Avenue','806','Mont','odio. Nam interdum enim non nisi. Aenean eget metus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A3H 5N5','6397 Phasellus Rd.','1450','Grimsby','Ut sagittis lobortis mauris. Suspendisse');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('29340','8499 Sed Ave','94','St. Austell','sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('88880','P.O. Box 815, 1550 Orci Road','613','Sint-Kruis','nunc interdum feugiat. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V9Z 3P3','Ap #126-966 Malesuada St.','1366','Vorselaar','Pellentesque tincidunt tempus risus. Donec egestas. Duis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('64275','878-5143 Fermentum Avenue','1251','Port Glasgow','porttitor scelerisque neque. Nullam nisl.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('92035','Ap #383-2765 Magna. Avenue','1122','Kampenhout','Praesent luctus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('33909','Ap #457-9066 Feugiat Street','1477','Liernu','purus, in molestie tortor nibh sit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('M2A 2P7','2797 Pretium Street','233','Lanark','Suspendisse non leo. Vivamus nibh dolor, nonummy ac,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F5Q 7W2','958-5453 Molestie St.','1031','Fort William','egestas. Fusce');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V2R 1O3','3451 Proin Avenue','877','Cap-Rouge','egestas lacinia.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('96325','P.O. Box 415, 6125 Et, Avenue','576','Incourt','nisi.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Y8G 8Z1','P.O. Box 584, 5111 Molestie Road','1118','Keiem','pede. Suspendisse dui. Fusce diam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('48382','Ap #835-7520 Non, Rd.','1012','Meeuwen-Gruitrode','egestas hendrerit neque. In ornare');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('N3K 2O0','551-3191 Fringilla Rd.','822','Toronto','senectus et netus et malesuada fames ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('05675','802-6702 Nec Rd.','718','Talgarth','Etiam gravida molestie arcu. Sed eu nibh vulputate mauris');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('78188','859-897 Pede. Road','268','Ramsey','Nulla aliquet. Proin velit. Sed malesuada augue');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('87289','854-2121 Ipsum. St.','42','Seraing','ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('01446','6641 Sed, Road','890','Victor Harbor','gravida mauris ut mi. Duis risus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z8F 5F7','1170 Ac Av.','231','Omal','sapien');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('K2S 4A3','1467 Semper Av.','273','Abingdon','eget tincidunt dui augue eu tellus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F1G 7A3','P.O. Box 775, 4159 Ut Rd.','50','Perth','ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('N9W 2K1','Ap #278-1446 Ut St.','155','Whyalla','Mauris non dui nec urna suscipit nonummy. Fusce fermentum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L1X 4Q1','P.O. Box 487, 7735 Sollicitudin Rd.','260','Uppingham. Cottesmore','aptent taciti sociosqu');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G5Q 1R5','P.O. Box 258, 4890 Mauris Rd.','550','Knoxville','posuere vulputate, lacus. Cras interdum. Nunc sollicitudin');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('O1F 3E8','856-7854 Donec Av.','637','Sint-Pieters-Kapelle','nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('79434','2066 Enim. St.','1346','Armstrong','nibh sit amet orci. Ut sagittis lobortis mauris.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('21723','372-7891 Fusce Av.','868','Mont','Donec felis orci, adipiscing');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P7F 6M2','Ap #686-1687 Pede. Avenue','482','Ruisbroek','ac mattis ornare, lectus ante dictum mi,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('83736','7899 Diam. Ave','916','Wondelgem','adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('88466','449-3585 Ipsum. St.','724','Evesham','Proin velit. Sed malesuada augue ut');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('14496','7625 Netus Avenue','651','Oxford County','erat vel pede blandit congue. In scelerisque scelerisque');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C7W 2H0','P.O. Box 184, 9316 Nec Av.','801','Marlborough','sem egestas blandit.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('E2U 5L0','Ap #576-4401 Ultricies Rd.','1130','Columbus','turpis. Aliquam adipiscing lobortis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G4J 3W3','6586 A, Av.','62','Venlo','hymenaeos. Mauris ut quam vel sapien imperdiet');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('03122','193-5955 Neque Av.','286','Cawdor','eu nulla at sem');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('74605','P.O. Box 615, 5377 Felis Rd.','1030','Guelph','dolor sit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('10603','6259 Lorem Road','827','Hinckley','Donec tempus, lorem fringilla ornare');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('N5G 6G6','Ap #266-2470 Ante Road','240','Owensboro','auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W8O 4I3','Ap #985-3229 Molestie St.','1460','Frederick','lorem, vehicula et, rutrum eu, ultrices sit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('54417','509-159 Urna. Avenue','389','Newbury','aliquet. Proin velit. Sed malesuada augue ut lacus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I6L 8R7','P.O. Box 852, 7354 Ante, St.','263','Lawton','Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('82193','4733 Diam Ave','915','Zutendaal','dictum sapien.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('77137','3041 Quisque Rd.','1352','Mont-Saint-Andr?','Proin non massa non ante');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('88696','4420 Magna. Street','497','Tongeren','ornare tortor at risus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A1O 3N7','Ap #565-9829 Nibh. Ave','857','Waret-lEv?que','arcu.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('62196','2567 Ante Road','187','Kettering','lectus, a sollicitudin orci sem');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('23295','7224 Ipsum St.','491','Alexandria','Nulla dignissim. Maecenas ornare');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V4O 9J5','Ap #725-3332 Rutrum Rd.','639','Port Alice','Etiam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('O8D 9Y4','6810 Ipsum Street','439','Belsele','Proin velit. Sed malesuada augue ut lacus. Nulla');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F7Q 3N3','P.O. Box 132, 609 Augue. Road','1026','Moircy','ultrices. Duis volutpat nunc sit amet metus. Aliquam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G9V 9K1','P.O. Box 646, 7624 In Street','176','New Haven','fermentum arcu. Vestibulum ante ipsum primis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L5G 1F0','2801 Proin Road','1309','Barrie','erat, in consectetuer ipsum nunc id enim. Curabitur massa.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('95023','835 Nonummy. Rd.','1399','Haddington','interdum enim non nisi. Aenean');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C4U 7F2','P.O. Box 859, 3096 Lorem, St.','904','Shawinigan','Praesent eu nulla at sem');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('M9D 7L3','Ap #623-6958 Eget Street','1193','Sydney','risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('B2H 1W9','P.O. Box 940, 3887 Vel Ave','931','Clare','tincidunt tempus risus. Donec egestas. Duis ac arcu.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I3H 8A5','861-5629 Sed St.','1499','Arendonk','sem, vitae aliquam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('04172','3200 Tellus Avenue','1081','Halifax','tempor, est ac mattis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W9F 7V2','P.O. Box 687, 6848 Nullam Avenue','1351','New Sarepta','aptent taciti sociosqu ad litora torquent');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('51682','P.O. Box 769, 3525 Molestie Avenue','1105','Sivry-Rance','Nullam ut nisi a odio semper cursus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('20309','274-691 Mauris St.','869','Lasne','penatibus et magnis dis parturient');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q3G 5I8','524-5844 Erat. Road','1238','Eisden','Duis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('N3Q 9W5','P.O. Box 958, 6768 Semper Road','1393','Provo','lectus quis massa. Mauris vestibulum, neque sed dictum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X8G 6Q7','894-7610 Etiam St.','619','Kilwinning','porttitor interdum. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q2H 2S0','Ap #175-4727 Est Rd.','379','Lampernisse','at lacus. Quisque purus sapien, gravida non, sollicitudin');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C4H 1A2','P.O. Box 166, 7315 Ut, St.','549','Torquay','ligula consectetuer rhoncus. Nullam velit dui, semper');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('H4X 2O4','P.O. Box 118, 8383 Morbi St.','797','Kessel','faucibus id, libero. Donec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F3T 9Q5','9931 Pede, St.','482','Zutendaal','sapien molestie orci tincidunt adipiscing. Mauris molestie');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('J8S 6L5','P.O. Box 835, 504 Adipiscing St.','843','Zaffelare','justo. Proin non massa non ante bibendum ullamcorper. Duis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('75871','446-6855 Metus St.','133','Saint-Jean-Geest','vitae aliquam eros turpis non enim. Mauris');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('80610','557 Cras Av.','754','Windsor','velit. Aliquam nisl. Nulla');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G4X 2S4','824-6678 Pede Street','718','Tay','vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C7J 3Z6','7626 Aliquet Road','932','Watson Lake','dapibus id,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('52352','Ap #347-6576 Aliquam St.','96','Kitscoty','risus, at fringilla purus mauris');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('80700','Ap #378-7310 Malesuada Av.','700','Marneffe','vitae risus. Duis a mi fringilla mi lacinia mattis.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('61117','4634 Quisque Rd.','1390','Gentinnes','eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L7P 7F3','8750 Mi St.','390','Anderlecht','urna. Nunc quis arcu vel');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V9P 8E0','P.O. Box 950, 413 Mi. Avenue','855','Keumiee','hendrerit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('40185','3824 Proin Road','782','Aisemont','elit elit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F9K 4U6','4947 Cursus Road','806','Holman','Vivamus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('22175','7340 Eget, Ave','1300','Prestatyn','rutrum eu, ultrices sit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q9U 7Z7','P.O. Box 207, 1290 Lectus St.','987','Sint-Pauwels','iaculis enim, sit amet ornare lectus justo eu arcu.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('44213','249-7189 Adipiscing Ave','634','Brodick','vitae velit egestas lacinia. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q3R 2U9','5329 Tortor Street','153','Greater Hobart','Suspendisse ac metus vitae velit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P4J 2X4','P.O. Box 526, 4958 Metus St.','291','Esen','venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('K9A 3R5','3357 Blandit Av.','200','Limal','Ut nec urna et arcu');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('64809','P.O. Box 210, 8335 Donec St.','578','Nuneaton','pretium aliquet,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('46266','730-5913 Sapien Rd.','54','Damme','Quisque ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L8M 4Y2','P.O. Box 679, 8501 A Avenue','1186','Comblain-la-Tour','Phasellus vitae mauris sit amet lorem semper auctor. Mauris');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z3Y 6T7','P.O. Box 734, 2110 Sed St.','1032','Driffield','luctus sit amet, faucibus ut, nulla. Cras eu');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('32131','P.O. Box 585, 8850 Conubia Rd.','233','Horsham','non, cursus non, egestas');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A9U 1M1','195-210 Dignissim Rd.','1115','Tongrinne','tortor nibh sit amet orci. Ut sagittis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I3A 3Q1','117-6776 Ornare. Street','647','Bonneville','velit. Pellentesque ultricies dignissim lacus. Aliquam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V6R 3Z3','321-9520 Amet, St.','307','Bouwel','sapien. Nunc pulvinar arcu et pede. Nunc sed orci');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('36037','Ap #133-5576 Est Av.','706','Ramsdonk','posuere cubilia Curae;');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F7F 3J0','Ap #324-2143 Fringilla Rd.','553','Sint-Niklaas','Nunc ullamcorper, velit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('B8X 8E6','562-4855 Euismod Rd.','919','Sluis','et, lacinia');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('83196','P.O. Box 326, 2137 Libero Rd.','955','Sint-Denijs-Westrem','sed, hendrerit a, arcu. Sed et');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('21676','P.O. Box 767, 5619 Dolor St.','1224','Laramie','eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('28392','P.O. Box 939, 2649 Odio. Avenue','508','Quenast','Maecenas');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('S1W 3O2','P.O. Box 362, 3234 Ipsum St.','839','Arviat','magna. Praesent interdum ligula eu enim. Etiam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('58685','Ap #319-8796 Nec, St.','1479','Helchteren','metus eu erat semper rutrum.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('33630','Ap #567-5152 Tellus Street','814','Teralfene','Quisque ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('80855','220-6548 Et Av.','641','Stourbridge','molestie in, tempus eu, ligula. Aenean euismod');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('T2H 3I8','Ap #345-2020 Augue, Ave','1050','100 Mile House','Nunc quis arcu vel quam dignissim pharetra. Nam ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('32588','1249 Ipsum Av.','373','Zutendaal','Suspendisse sagittis. Nullam vitae');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('60935','P.O. Box 716, 2863 Elit, Rd.','217','Recogne','a neque. Nullam ut nisi a odio');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('U7O 1E9','234-4626 Aliquam Av.','362','Tamworth','cubilia Curae;');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W7Y 5Q3','P.O. Box 160, 1928 Duis Avenue','1195','Zuienkerke','nostra, per inceptos');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('77822','487-3798 Mi. Rd.','1072','Boninne','adipiscing ligula. Aenean gravida nunc sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('55957','P.O. Box 362, 1593 Elit. Ave','1154','Kasterlee','amet, dapibus id, blandit at, nisi.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X3U 5O2','P.O. Box 543, 9456 Aenean Rd.','507','Tourinnes-la-Grosse','at, velit. Cras lorem lorem,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I6L 3E4','P.O. Box 439, 4768 Curae; St.','481','Tain','mauris ipsum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I8G 6R0','Ap #374-4641 Lorem Road','1451','Cedar Rapids','at pretium aliquet, metus urna convallis erat, eget');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C6Y 8E1','4752 Lorem, St.','1471','Port Hope','a ultricies adipiscing,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('12254','304-8252 Fusce Street','830','Beho','eget odio. Aliquam vulputate ullamcorper magna. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('85280','Ap #458-3675 Ultricies Road','686','Gooik','tristique pharetra. Quisque ac libero nec ligula');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('95841','P.O. Box 678, 4616 Primis Ave','305','Aklavik','iaculis odio. Nam interdum enim non nisi. Aenean eget');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('22702','Ap #644-3085 Metus Street','1332','Sandy','Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('56710','P.O. Box 871, 5865 Gravida Road','1071','Breda','nec tempus mauris erat eget ipsum. Suspendisse');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('69161','P.O. Box 605, 7540 Consectetuer St.','298','Birmingham','mauris. Integer');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('93600','9632 Euismod Ave','53','Olympia','quis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P5F 5S5','P.O. Box 433, 6412 Adipiscing. Avenue','1209','Springdale','Mauris vestibulum, neque sed dictum eleifend,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('69341','506-4970 Aliquam Rd.','588','Lavoir','neque sed dictum eleifend, nunc risus varius orci, in');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('29219','4683 Dui Road','1461','Dworp','ornare, facilisis eget, ipsum. Donec sollicitudin');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('14765','Ap #964-8942 Ligula. Street','590','Peutie','eu tellus. Phasellus elit pede,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('U8O 2Z0','Ap #253-971 At Av.','941','Campbeltown','tempus eu, ligula. Aenean euismod mauris');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('85428','Ap #876-9395 Suspendisse Av.','1142','Murray Bridge','cubilia Curae;');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Y6G 2B6','4959 Sollicitudin Street','111','Dawson Creek','dui lectus rutrum urna, nec luctus felis purus ac tellus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V3Q 9C4','6416 Turpis. St.','866','Tay','parturient montes, nascetur');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F9B 4I3','P.O. Box 421, 7751 Sociis Road','181','Chippenham','dui. Cum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('98344','154-6924 Tortor, St.','417','Dorchester','odio, auctor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L2G 2F9','P.O. Box 478, 5607 Pede Rd.','631','Spijkenisse','per inceptos hymenaeos. Mauris ut quam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('57177','P.O. Box 350, 2403 Posuere Road','1246','Macon','varius orci, in');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('B9C 8V4','666-3177 Euismod Avenue','432','Anlier','sagittis. Duis gravida. Praesent');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('00851','P.O. Box 565, 2643 Metus Rd.','578','Monceau-Imbrechies','rutrum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P7M 9U9','P.O. Box 642, 3266 Ridiculus Avenue','1274','Fl?nu','amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A5O 3G8','P.O. Box 832, 4782 Mollis Ave','1450','Hulshout','non enim commodo hendrerit. Donec porttitor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('41670','816-6747 Nam Avenue','923','Warren','Donec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X8P 1Y7','9959 Mauris Street','406','Massenhoven','faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('K3R 2S2','Ap #951-9598 Ipsum Ave','527','Opwijk','gravida non, sollicitudin a, malesuada');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q9X 3J9','7109 Vulputate Street','1017','Sint-Pieters-Kapelle','pellentesque, tellus sem');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W7D 4L1','3484 Risus. St.','1205','Jemeppe-sur-Meuse','vitae, aliquet nec, imperdiet');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I8N 9E0','7534 Fermentum Rd.','1346','Omaha','imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('T5C 5B4','213-2944 Ornare, Ave','907','Tuscaloosa','lectus convallis est, vitae sodales nisi magna sed dui. Fusce');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('46300','407 Sodales Avenue','1329','Aklavik','neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('09367','P.O. Box 515, 6137 Dolor St.','674','Whitby','pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('85450','113-6672 Quis, Ave','1036','Roxburgh','in sodales elit erat vitae risus. Duis a mi fringilla');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C6V 7L6','6292 Neque. St.','871','Hann?che','Donec luctus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('20062','P.O. Box 258, 7666 Sit St.','714','Tourinne','mauris sit amet lorem semper auctor. Mauris vel turpis.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F2J 6T6','876-9016 Donec Street','1245','King Township','Donec porttitor tellus non magna. Nam ligula elit, pretium');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('05984','P.O. Box 576, 2081 Pede. Road','482','Beerst','semper erat, in consectetuer ipsum nunc id enim. Curabitur massa.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X4H 8A4','Ap #424-1100 Neque Street','1051','Toowoomba','nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('82438','P.O. Box 555, 9758 Etiam Rd.','1238','H?villers','vulputate, lacus. Cras interdum. Nunc sollicitudin');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X5C 9F9','P.O. Box 162, 3856 Magnis Avenue','1321','Soye','urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P5E 7G4','206-1093 Luctus Street','1091','Montrose','sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('17667','749-4594 Ut Road','713','Xhoris','ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('41506','1842 Nunc Rd.','547','Bressoux','Integer vitae nibh. Donec est mauris, rhoncus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A4L 9V8','Ap #706-5343 Nam St.','535','Rothesay','erat vel pede');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('24521','3201 Vulputate, Road','1324','Shippagan','tellus id nunc interdum feugiat. Sed nec metus facilisis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('N1Z 4D4','121-9820 In, Road','1081','Merksem','mus. Donec dignissim');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('E2O 9J8','4977 Auctor Ave','830','Vlezenbeek','hendrerit id,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('76142','8187 Faucibus Ave','190','Falmouth','risus varius orci, in consequat enim diam vel arcu.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('B3O 1O4','Ap #479-8755 Luctus Av.','1378','Wangaratta','magna. Lorem');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C7I 9Q3','4590 Rutrum Avenue','1339','Lourdes','nonummy. Fusce fermentum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('R7J 3P1','938-259 Eu Street','1359','Greenlaw','In mi pede, nonummy ut, molestie');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('41261','583-7762 Nulla Road','473','D?gelis','sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('42333','2378 Gravida Ave','751','Bloomington','Nullam vitae diam. Proin dolor.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('77118','6891 Non St.','431','Maidenhead','dignissim pharetra. Nam ac nulla. In tincidunt');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X3T 6L5','259-9370 A, Ave','1493','New Orleans','Mauris vel turpis. Aliquam adipiscing lobortis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('50132','175-852 Ligula St.','1012','Jonesboro','purus sapien, gravida non, sollicitudin a,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('00048','9164 Nam Rd.','781','St. Thomas','faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('45543','Ap #377-3940 Enim Rd.','395','Buxton','Integer vitae nibh. Donec est mauris, rhoncus id,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('78283','7092 Risus, Av.','1346','Whithorn','magnis dis parturient montes, nascetur');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('58489','2712 Tempus Road','661','Sint-Kruis-Winkel','sodales nisi magna');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('N4K 4L5','P.O. Box 666, 8766 Nonummy Rd.','489','Poppel','Cum sociis natoque penatibus et magnis dis parturient montes,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('89225','455-7347 Elementum, Ave','851','Affligem','sociis natoque penatibus et magnis dis parturient montes, nascetur');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('07586','481-452 Sed Ave','1486','Wimbledon','sagittis lobortis mauris. Suspendisse aliquet molestie tellus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('C9W 4B0','P.O. Box 840, 3732 Consequat Rd.','869','Denderbelle','vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('40406','P.O. Box 397, 3185 Quisque Rd.','493','Lot','Vivamus non lorem vitae odio sagittis semper. Nam tempor diam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I1A 6E7','P.O. Box 777, 7608 Fusce Avenue','98','Dampicourt','odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L6D 3R5','Ap #498-9104 Justo. Av.','92','Saint-L?ger','quam vel sapien imperdiet ornare. In');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A3B 9B8','600-5310 Inceptos Road','115','Montigny-le-Tilleul','orci,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('M3M 5W3','262-8208 Tempus Street','256','Zelem','non, egestas a, dui.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('17707','Ap #813-6636 Tincidunt Av.','754','Moerzeke','tempor, est ac mattis semper, dui lectus rutrum urna,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('18571','P.O. Box 643, 7781 Ultrices Street','1155','Barrhead','habitant morbi tristique senectus et netus et');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('O2M 4W3','972-8811 Elit. Av.','886','Ammanford','Phasellus elit pede, malesuada vel, venenatis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('75813','8804 Duis Ave','1148','Venlo','parturient montes,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Y2Y 6I2','7158 Netus Ave','1086','Newcastle','consequat dolor vitae dolor. Donec fringilla. Donec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('42624','169-1566 Non Rd.','378','Enines','leo.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('62782','6417 Facilisis Street','789','Harrisburg','diam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('M6A 9L5','P.O. Box 824, 9982 Tristique St.','870','Drogenbos','Suspendisse ac metus vitae velit egestas lacinia. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('37920','814-2095 Ullamcorper. Road','653','Ramsel','auctor quis, tristique ac,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('19239','4254 Non, St.','957','Lives-sur-Meuse','amet lorem');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X6I 7J9','237-7815 Adipiscing St.','76','Emmen','facilisis eget,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('57297','6106 Tortor Ave','1414','Redlands','Phasellus vitae mauris sit amet lorem semper auctor.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('28420','Ap #611-1828 Nunc Ave','92','Green Bay','aliquet libero. Integer in magna. Phasellus dolor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('87457','803 Suscipit Ave','986','Fochabers','lectus. Cum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A9J 9O9','Ap #476-9038 Metus St.','1277','Cromer','sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('U5H 4C0','P.O. Box 655, 821 Donec Rd.','994','Sint-Stevens-Woluwe','convallis, ante lectus convallis est, vitae sodales');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('96636','Ap #935-5139 Vivamus St.','599','Greater Sudbury','dictum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('88244','Ap #144-3431 Scelerisque, Rd.','900','Rance','eu nibh vulputate mauris sagittis placerat. Cras');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('J6O 4Y9','495-4551 Et Rd.','144','Bossut-Gottechain','Nullam ut nisi a odio semper cursus. Integer mollis. Integer');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('60942','7133 Donec Street','460','Ehein','condimentum. Donec at');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V2J 6M6','Ap #470-2779 Feugiat. Road','709','Kailua','sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q9A 5C0','Ap #752-6124 Quis Ave','290','Stonehaven','eget, volutpat');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G9U 7O2','4427 Vitae Rd.','1496','Cwmbran','sit amet');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F1D 5D1','7321 Metus. Street','880','Beausejour','tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Y4Y 6A7','P.O. Box 790, 9275 Tincidunt Street','670','Doetinchem','cubilia Curae; Donec tincidunt. Donec vitae erat vel');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('T9R 9I1','P.O. Box 427, 4510 Odio Street','1004','Armadale','pede. Nunc sed orci lobortis augue');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('20042','112-357 Nunc St.','1481','Springdale','nisi. Mauris nulla. Integer');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G8R 1X8','934-753 Consequat Road','1485','Meeswijk','justo. Praesent');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('97464','951-1555 Eget Av.','199','Kings Lynn','Nam tempor diam dictum sapien.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('80541','Ap #635-1042 Vitae Ave','764','Gravelbourg','a, scelerisque sed, sapien. Nunc pulvinar arcu et');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('N4K 8B7','4412 Ridiculus Street','694','Limerl?','blandit at, nisi.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('36204','P.O. Box 490, 2299 Est Road','1351','Murdochville','elit pede,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('82850','P.O. Box 330, 9239 Urna. Rd.','1038','Meeswijk','rutrum eu, ultrices sit amet, risus. Donec nibh');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('21241','P.O. Box 660, 7152 Iaculis Av.','1432','Pointe-au-Pic','eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('86213','822-2087 Dapibus Street','606','Whithorn','non massa non ante');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('93912','630-6298 Cubilia Road','1329','Fallais','pede nec ante');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('V8J 7W8','Ap #984-4531 Massa St.','1408','Arviat','posuere vulputate, lacus. Cras interdum. Nunc sollicitudin');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('32446','6646 Sociosqu Ave','385','Felixstowe','urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('24017','P.O. Box 760, 365 Laoreet Rd.','474','Hattem','urna. Nunc quis arcu');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('K4I 5I9','4930 Pellentesque Street','432','Swadlincote','vitae semper egestas, urna');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('94869','P.O. Box 714, 8937 Fusce Ave','259','Machynlleth','vulputate eu, odio. Phasellus at');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('K8D 2J0','356 Lectus Rd.','784','Fallais','Donec felis orci, adipiscing non, luctus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('27596','P.O. Box 721, 3983 Tincidunt Ave','393','Monceau-Imbrechies','ipsum nunc id enim. Curabitur massa.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('T4F 7E4','Ap #567-8359 Eget, Rd.','1388','Stockton-on-Tees','tempor augue ac ipsum. Phasellus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('10811','4405 Dictum Street','235','Montleban','imperdiet dictum magna. Ut tincidunt');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('94353','8762 Risus St.','637','Bathurst','Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L3D 7G6','Ap #446-8696 Feugiat Road','9','Great Yarmouth','consectetuer adipiscing elit. Etiam laoreet, libero et tristique');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('U9I 2R1','Ap #522-4051 Vivamus Street','820','Tulita','neque');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('82371','333 Quis Rd.','831','Sheffield','elementum at,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A4F 1O2','6284 Enim. Rd.','84','Delft','facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('H9M 8M4','Ap #559-2810 Cursus Av.','925','Sioux City','a nunc. In at pede. Cras vulputate velit eu sem.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('89064','576-679 Tincidunt Rd.','86','Cap-Rouge','In mi pede, nonummy ut, molestie in, tempus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('49896','Ap #383-3698 Sapien Av.','1105','Henis','risus. Donec egestas. Duis ac arcu. Nunc');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('51176','Ap #935-914 Non Avenue','884','Crowsnest Pass','nec ligula consectetuer rhoncus. Nullam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('72836','Ap #945-3292 Lacus Rd.','602','Smetlede','Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Y7Z 9G4','P.O. Box 445, 5009 Cursus. Avenue','1046','Houtvenne','elit,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('S8V 2H2','8962 Cursus Ave','223','Tamworth','lacus. Mauris non dui nec urna');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('95423','Ap #328-2827 Purus St.','147','Rhyl','Maecenas ornare egestas ligula.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L1O 8R7','607 Commodo Avenue','490','Lapscheure','augue scelerisque mollis. Phasellus libero');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('O3E 4E8','979-4009 Pede. Ave','1034','Savannah','ac facilisis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('01387','273-6326 Orci Av.','208','Wetteren','Integer in magna. Phasellus dolor elit, pellentesque a,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('57737','552-3863 Et Rd.','1001','Vezin','facilisis, magna');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('20713','P.O. Box 345, 4583 Felis. Street','870','Redcliffe','Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('H6B 5L3','P.O. Box 237, 919 Pharetra. Avenue','844','Hull','at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('59742','585-5482 Ut, St.','257','Ruddervoorde','eu tellus eu augue porttitor interdum. Sed auctor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X4B 6G4','455-3266 Faucibus Street','153','Orlando','montes, nascetur ridiculus mus. Proin vel arcu eu odio');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('85672','193-9096 Nascetur Road','1455','Jacksonville','Proin sed turpis nec mauris blandit mattis. Cras');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('07552','862 Elit Ave','3','Grande Prairie','tellus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W6H 3V0','Ap #956-609 Nulla. Rd.','586','Lokeren','diam. Duis mi');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('93596','686-5607 Egestas Street','767','Woerden','posuere cubilia Curae; Donec tincidunt.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('45715','7576 Nunc Rd.','181','Zuienkerke','volutpat nunc sit amet metus. Aliquam erat');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q3R 4A6','8711 Feugiat. Rd.','246','Renfrew','eget metus eu erat semper rutrum. Fusce');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('H1M 1P1','675-3802 A, Road','386','Kearney','nibh.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('44142','P.O. Box 173, 5619 Habitant Rd.','462','Springfield','vitae odio sagittis semper.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('25070','Ap #827-1612 Sed Rd.','462','Pickering','velit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('13028','722-8370 Tincidunt Ave','1376','Cranbrook','Nam interdum enim non nisi. Aenean eget metus. In nec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z9P 1N8','P.O. Box 136, 8664 Tincidunt Rd.','28','North Vancouver','pede. Cum sociis natoque penatibus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('12756','825-5534 Dui, St.','114','Damme','penatibus et magnis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X7O 4B2','403-4919 Eget St.','1120','Linlithgow','Aliquam ultrices iaculis odio.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('D2D 3B8','402-887 Eros Av.','507','Erie','Aliquam ornare, libero at auctor ullamcorper, nisl');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q4A 7L4','963-4709 Auctor. St.','819','Newton Stewart','Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('D3S 5N9','927-1431 Lacinia. St.','51','Saint-G?ry','bibendum fermentum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('91993','3763 Sed Street','1430','Sint-Kruis-Winkel','iaculis enim, sit amet ornare lectus justo eu arcu. Morbi');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('W8E 5W0','P.O. Box 751, 6307 Quis, St.','69','Rotterdam','orci luctus et ultrices posuere cubilia Curae; Donec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('K6W 9O3','427-4956 Sagittis Rd.','1202','Devon','sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('D8Q 8G2','P.O. Box 573, 4541 Eu, Ave','265','Hondelange','facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('09053','Ap #352-6886 Egestas. Road','1366','Annan','Nunc quis arcu vel quam dignissim');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('74900','Ap #577-4406 Dui Rd.','1101','High Wycombe','eget mollis lectus pede et');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('12260','238 Dignissim. Road','1073','Provost','Quisque ornare tortor at risus. Nunc ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('J4P 2O8','224 Fusce Rd.','708','Jackson','sit amet, consectetuer adipiscing');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('D9P 4L2','555-6975 Tristique Street','1119','Columbus','nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('O9U 1N5','P.O. Box 667, 9413 Neque Rd.','55','Belgrade','lorem ac');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('64408','P.O. Box 438, 813 Ut, St.','343','Fredericton','pharetra. Quisque ac libero nec ligula');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('14195','Ap #867-5182 Nec Avenue','1485','Li?ge','tincidunt pede ac urna.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('96083','P.O. Box 300, 3712 Erat St.','564','Steendorp','Nunc mauris sapien, cursus in, hendrerit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('03368','7771 Molestie Ave','357','Gatineau','at, nisi. Cum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('F1P 7V1','Ap #220-4627 Eget Road','1397','Keith','nunc interdum feugiat. Sed nec metus facilisis lorem tristique');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('P9B 2X7','Ap #120-9678 Diam Rd.','205','North Las Vegas','tempor, est ac mattis semper, dui');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('83553','P.O. Box 407, 4331 Mattis. Rd.','568','Alert Bay','orci. Ut semper pretium neque.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('04324','P.O. Box 875, 8605 Malesuada Av.','986','Assen','augue ut lacus. Nulla tincidunt, neque vitae semper');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('93099','300-5349 Natoque Rd.','977','Ophoven','Nunc ac sem ut dolor dapibus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('73447','Ap #301-6608 Vitae Rd.','24','Flin Flon','sem ut cursus luctus, ipsum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('94601','Ap #603-1774 Fringilla Road','1309','Ellikom','risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('92500','P.O. Box 967, 4872 In Rd.','1306','Gold Coast','diam. Sed diam lorem, auctor quis, tristique ac, eleifend');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A3F 8V9','Ap #499-3259 Erat, Ave','383','Bodmin','Quisque ornare tortor at risus. Nunc ac sem ut dolor');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('67994','7521 Et Avenue','1391','Roxboro','ipsum non arcu.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('23066','9592 Enim. Avenue','540','Esneux','dui. Fusce diam nunc, ullamcorper');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z9J 3P4','774-3364 Sed St.','864','Dalkeith','In nec orci. Donec nibh. Quisque nonummy ipsum non arcu.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('16657','P.O. Box 152, 9134 Orci St.','599','Côte-Saint-Luc','in, hendrerit consectetuer, cursus et, magna. Praesent interdum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('84685','Ap #912-2512 Vitae Rd.','1015','Moorsele','in magna. Phasellus dolor elit,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Q9Q 4R4','746 Magna Ave','589','Fremantle','pharetra. Nam ac nulla.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('69129','P.O. Box 699, 9006 Lorem Street','770','Ellesmere Port','dui. Suspendisse ac metus vitae');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('76537','Ap #827-7481 Sed Rd.','120','Wondelgem','ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('61513','431-9000 Cum St.','1154','Knighton','Nulla semper tellus id nunc interdum feugiat. Sed nec');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X3T 7L4','4999 Fusce Ave','708','Mackay','Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('88157','P.O. Box 261, 9747 Accumsan Rd.','1388','Whithorn','lectus sit amet luctus vulputate, nisi sem semper erat,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('K9F 4B9','9210 Luctus. Road','1141','Onze-Lieve-Vrouw-Lombeek','elementum purus, accumsan interdum libero');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('52766','P.O. Box 917, 2389 Praesent Avenue','417','Dornoch','ut cursus luctus, ipsum leo elementum sem, vitae aliquam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('H1A 7I0','2156 Et St.','31','Eghezee','montes,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('72068','7986 Suspendisse Av.','989','Sanquhar','Sed id risus quis diam luctus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('05031','P.O. Box 390, 2655 Nibh St.','933','Sloten','elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('83016','785-5353 Ut St.','998','Cairns','nunc sit amet');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('24042','Ap #616-6936 A Street','515','Oakham','feugiat metus sit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('78222','301-6652 Vehicula St.','384','Zaanstad','ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('X3A 3U8','453-4225 Dis St.','57','Murdochville','luctus et ultrices posuere cubilia');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('J2H 2X7','6425 At, Ave','315','Stirling','metus. Aliquam erat volutpat.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('48552','2795 Lorem St.','321','H?l?cine','dictum ultricies ligula. Nullam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('S6A 9O0','P.O. Box 275, 6001 Turpis St.','823','Laarne','arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('73422','Ap #451-9769 Dictum Street','228','Saint-Remy-Geest','orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('L5U 1F9','7037 Lorem, Ave','78','Limelette','imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('34253','P.O. Box 883, 3151 Proin Rd.','1051','Kapolei','arcu ac orci. Ut semper pretium neque. Morbi quis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('R4Q 8X2','144-5638 Est Av.','205','Chantemelle','ac arcu. Nunc mauris. Morbi');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('41014','Ap #346-8196 Dapibus Rd.','993','Louisville','molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('D2V 5S9','Ap #757-6281 Morbi St.','1056','Dworp','at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('O1S 9Q2','Ap #246-5041 Non St.','732','Grivegn?e','tempor arcu. Vestibulum ut eros non');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('G4R 3E8','644-4805 Aliquam Street','653','Jette','nisi sem semper erat, in consectetuer ipsum');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('43407','7759 Velit St.','232','Meise','et, lacinia');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('I1N 4Q7','326-2089 Vehicula Rd.','755','Morinville','est. Nunc');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('Z1X 8J6','3515 Pharetra. St.','1236','Prestatyn','eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula.');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('72021','Ap #364-4449 Lacinia St.','754','Leffinge','eu augue');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('34224','P.O. Box 967, 7895 Sapien Street','1249','Gijzelbrechtegem','natoque penatibus et magnis dis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('11005','275-584 Nec Rd.','778','Martelange','id nunc interdum feugiat. Sed');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('53535','Ap #629-5705 Imperdiet St.','1468','Stirling','sem magna nec quam. Curabitur vel lectus. Cum sociis natoque');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('83915','Ap #211-9785 Est Ave','349','Nakusp','cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('S5M 2M0','P.O. Box 159, 4683 Pede, St.','190','Boness','a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('A5V 8M9','1879 Quisque Rd.','845','Taber','eu tellus');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('T9M 9X1','P.O. Box 632, 2019 Fringilla Road','1428','Sanquhar','mi fringilla mi lacinia mattis. Integer eu lacus. Quisque');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('D2X 2U1','5812 Phasellus St.','561','Vorselaar','porta elit,');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('74848','P.O. Box 156, 1569 Arcu. St.','581','Wijshagen','dapibus quam quis diam. Pellentesque habitant morbi');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('60792','968-6360 Hendrerit St.','1204','Leffinge','tellus. Phasellus elit pede, malesuada vel, venenatis');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('D1L 5X7','Ap #467-4090 Iaculis Rd.','1221','Coalville','at sem molestie sodales. Mauris');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('21960','617-682 Scelerisque St.','893','Worthing','amet, consectetuer adipiscing elit. Curabitur');
INSERT INTO Adresa (psc,ulice,cisloPopisne,mesto,poznamka) VALUES ('76252','454-3549 Diam. Street','210','Langenburg','Proin mi. Aliquam gravida mauris ut mi. Duis risus');
