INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tellus','pretium','936','pharetra, felis eget');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nec','dignissim','654','vel,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dolor.','aliquet,','932','ut ipsum ac mi eleifend egestas. Sed pharetra,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Vestibulum','Phasellus','665','scelerisque neque sed sem');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('parturient','mattis.','856','sed,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vel','diam','919','Fusce diam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ut','dolor,','1113','dapibus quam quis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Proin','parturient','1091','Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mi','ultrices,','676','Aliquam fringilla cursus purus. Nullam scelerisque neque sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Donec','molestie','852','sapien. Aenean massa. Integer vitae');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('luctus','tincidunt,','735','Nullam ut nisi a odio semper cursus. Integer mollis.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('erat','sapien','792','faucibus ut, nulla. Cras eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Cras','tellus','685','mi. Aliquam gravida mauris ut mi. Duis risus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mi.','pellentesque','1061','fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('massa.','dui,','1120','Phasellus nulla. Integer vulputate, risus a ultricies');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('quam','vel','665','Sed auctor odio a purus. Duis elementum, dui');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('cubilia','eget','1014','ante bibendum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sem','auctor','704','et, eros. Proin ultrices. Duis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('natoque','luctus,','825','ac mattis velit justo nec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('penatibus','facilisis','925','augue eu tellus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Sed','ipsum','774','Curabitur dictum. Phasellus in felis. Nulla tempor augue');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('magnis','dictum','747','nisi. Mauris nulla. Integer urna. Vivamus molestie');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Integer','dictum','788','mauris id sapien. Cras dolor dolor,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Donec','nec,','1111','Cum sociis natoque penatibus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dolor','nisi','1068','at sem molestie sodales.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sociosqu','nibh','676','non sapien molestie');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu','Proin','984','non');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Pellentesque','Mauris','822','purus ac tellus. Suspendisse sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lacus.','quam','777','nec, imperdiet nec,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dictum','aliquet','900','nunc risus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('a','Nulla','816','Vestibulum ante');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Donec','ornare','1002','fringilla');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('adipiscing','nec','1072','velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Integer','ut,','735','lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('fames','auctor','678','lobortis. Class aptent taciti sociosqu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('orci,','tellus.','998','Phasellus libero mauris, aliquam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('varius','amet','820','Aliquam ultrices iaculis odio.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('gravida','imperdiet','727','eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Curae;','aliquet,','1087','et ultrices posuere cubilia Curae;');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('id','lacus.','766','luctus felis purus ac tellus. Suspendisse sed dolor. Fusce');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dui,','quam.','722','diam. Proin dolor. Nulla');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Integer','turpis.','1109','amet luctus vulputate, nisi sem semper erat, in consectetuer');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Nunc','diam.','1013','Nunc pulvinar arcu et');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tellus','Nam','823','Curabitur ut odio vel');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('a,','Fusce','1032','magnis dis parturient montes, nascetur ridiculus mus. Aenean');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Aliquam','rutrum','1025','iaculis enim, sit amet ornare lectus justo eu arcu. Morbi');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ipsum','at','847','rhoncus. Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Ut','Suspendisse','964','interdum ligula eu enim. Etiam imperdiet dictum magna.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Aliquam','consectetuer','824','egestas. Sed pharetra, felis eget varius');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('quis','aliquam','1123','non, hendrerit id, ante. Nunc mauris sapien, cursus in,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('turpis.','purus.','956','dui, nec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sociis','molestie.','685','eget, venenatis a, magna. Lorem ipsum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sed','tellus.','664','lacus vestibulum lorem, sit amet ultricies sem magna');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('purus','Donec','795','habitant morbi tristique senectus et netus et');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('augue.','dictum','807','urna convallis erat, eget');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('enim,','tellus.','1062','a');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('rutrum.','odio','809','sapien. Cras dolor dolor, tempus non, lacinia');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ante','ultrices','947','In ornare sagittis felis. Donec tempor, est ac mattis semper,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Quisque','magna.','835','sed, facilisis vitae, orci. Phasellus dapibus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('consectetuer','nibh','1045','Nam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eget','pede.','774','Curabitur consequat, lectus sit amet luctus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Duis','Aliquam','801','Proin vel arcu eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('aliquet','nibh','825','malesuada. Integer id');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('arcu.','egestas.','912','erat eget');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ipsum','Nam','996','Aliquam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ornare','tempus','639','enim,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Ut','leo,','885','ullamcorper, nisl arcu iaculis enim, sit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('volutpat.','nibh.','956','Cum sociis natoque penatibus et');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('venenatis','sapien','1074','Proin nisl sem, consequat nec, mollis vitae, posuere');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nunc.','purus,','809','elit, pharetra ut, pharetra sed, hendrerit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ac','pellentesque.','673','at augue id ante dictum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('risus.','interdum','990','mi, ac mattis velit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('turpis','lacus.','763','non ante bibendum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('malesuada','Praesent','830','amet diam eu dolor egestas rhoncus. Proin nisl sem,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tempus','nunc.','1043','imperdiet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ornare,','aliquet','964','odio. Phasellus at augue id ante dictum cursus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('purus.','Nunc','748','erat volutpat. Nulla dignissim. Maecenas ornare');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('non,','erat','902','nec, euismod in,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('posuere','metus','997','amet lorem semper');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('et','orci','805','diam vel arcu. Curabitur ut odio vel');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('fringilla,','eget','758','est ac facilisis facilisis, magna tellus faucibus leo, in');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vitae','vulputate,','958','nulla. In tincidunt congue turpis.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dictum','dictum','889','vulputate,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mus.','blandit','760','vulputate ullamcorper magna.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ac,','ac','862','natoque penatibus et magnis dis parturient');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vehicula','nibh','973','dui');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('erat','in,','708','magna tellus faucibus leo, in lobortis tellus justo');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Cras','Quisque','893','sit amet ultricies sem magna nec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Vivamus','mi,','726','orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Pellentesque','quam','752','ipsum non');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ipsum.','egestas','671','iaculis enim, sit amet ornare lectus justo eu arcu.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu','volutpat.','799','Suspendisse aliquet, sem ut cursus luctus,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('aliquam','pede','800','blandit viverra. Donec tempus, lorem fringilla ornare');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu,','dignissim','1122','erat. Etiam vestibulum massa rutrum magna. Cras');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('turpis','ipsum','975','elit,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Vivamus','Nunc','1051','felis orci,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nunc','lorem','966','ipsum nunc id enim. Curabitur massa. Vestibulum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('posuere,','nisl','644','velit egestas lacinia.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sem.','Nunc','947','convallis, ante lectus convallis est, vitae sodales nisi magna sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('at','parturient','1036','ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('elementum','lacus.','1091','vitae semper egestas, urna justo faucibus lectus, a');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('enim','vel','1032','Nullam velit dui,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ac','ipsum','838','ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vel','cursus','1009','Praesent eu nulla at sem molestie');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('aliquam,','lobortis','969','odio');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ipsum.','purus.','683','mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('risus.','gravida.','834','magna, malesuada vel, convallis in, cursus et, eros.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Nullam','dui','699','sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nibh.','molestie.','1096','tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('quis','enim,','872','enim, condimentum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sapien','Duis','1017','pellentesque. Sed dictum. Proin eget');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('quis,','vitae','831','Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('orci','iaculis','687','Nullam ut nisi a odio');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Phasellus','velit','706','a, arcu.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('adipiscing','nisi','1059','ac nulla. In tincidunt congue turpis.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('elementum','dolor','740','pretium aliquet, metus urna convallis erat, eget');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('a','Phasellus','754','posuere vulputate, lacus. Cras interdum.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('torquent','magna','760','eu erat semper rutrum. Fusce dolor');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ultricies','condimentum.','1049','eget');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Sed','ultrices','1047','mattis semper,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Aliquam','magna.','967','mus. Proin vel arcu eu odio');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ut','dictum','861','Donec felis orci, adipiscing non, luctus sit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('aliquet','mollis.','747','pede. Cras vulputate velit eu sem. Pellentesque ut ipsum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sem','dolor','694','a, arcu. Sed et libero.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('id','purus.','886','non nisi. Aenean');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('urna','tempor','672','dui. Cum sociis natoque penatibus et magnis dis parturient');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('fermentum','lectus','670','urna justo faucibus lectus, a');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dui','arcu.','819','ullamcorper. Duis at lacus. Quisque');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('magna.','nunc','785','adipiscing elit. Curabitur sed tortor.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nec,','dui.','1113','Praesent interdum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu','metus.','1064','augue id ante dictum cursus. Nunc mauris elit,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('bibendum','Mauris','804','magna. Phasellus dolor');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Lorem','eros','866','eu metus. In lorem. Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pede,','molestie','1085','ipsum. Phasellus vitae mauris sit amet lorem semper');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('augue','et','1021','orci. Ut semper');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('orci','metus.','931','mattis velit justo nec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pede,','lorem','796','ac libero nec ligula consectetuer');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('iaculis','eu','743','mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ac','tristique','1055','bibendum. Donec felis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vel','sociosqu','727','pede. Cras vulputate');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Praesent','erat.','1006','feugiat nec, diam. Duis mi enim, condimentum eget,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('metus.','libero.','829','ultrices');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('placerat','est','662','Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('facilisis','lorem,','735','sit amet lorem semper auctor. Mauris vel turpis. Aliquam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Cras','sem','970','nunc ac mattis ornare, lectus ante dictum mi, ac');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('volutpat','varius','1118','Donec fringilla. Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('semper','metus.','740','semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Aenean','et','961','lorem ac risus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('convallis','Sed','715','eu, odio. Phasellus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('et','mi','660','arcu iaculis enim,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('a,','tempor','1071','penatibus et magnis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nibh','elit,','1016','eget, venenatis a, magna. Lorem');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('massa.','ligula','709','mollis. Duis sit amet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Maecenas','nibh','1005','a, arcu. Sed et libero. Proin mi. Aliquam gravida');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mi,','Duis','638','velit dui, semper et,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('molestie','felis','947','est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('odio.','natoque','903','odio. Aliquam vulputate ullamcorper magna. Sed eu eros.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('justo.','ut,','800','aliquet. Proin velit. Sed malesuada augue ut');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('urna','ante','657','nec mauris blandit mattis.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Duis','in','1058','Donec dignissim magna');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('enim','turpis.','1092','risus. In mi pede, nonummy');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Aliquam','scelerisque','679','eros nec tellus. Nunc lectus pede, ultrices a, auctor');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nisi.','mauris','1109','eu dolor egestas');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('gravida','at,','998','mollis. Duis sit amet diam eu dolor egestas rhoncus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tempus,','metus.','884','molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('purus.','Maecenas','1071','morbi tristique senectus et netus et');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('facilisi.','In','709','neque');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tellus','parturient','775','amet ornare lectus justo eu arcu. Morbi sit amet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ante','Aliquam','791','neque');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tincidunt','magna','880','cursus. Nunc mauris elit,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('egestas,','in,','728','malesuada id, erat. Etiam vestibulum massa rutrum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pede','purus','683','vitae sodales nisi magna');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nascetur','vel','1077','in faucibus orci luctus et ultrices posuere');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lectus','amet','747','neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('molestie','interdum','733','mauris sit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Ut','lacinia','987','adipiscing elit. Aliquam auctor, velit eget laoreet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tristique','vestibulum.','872','Proin mi. Aliquam gravida mauris');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Mauris','Nam','661','Integer id magna et ipsum cursus vestibulum.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sit','euismod','888','a');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('feugiat.','ac','794','semper erat, in consectetuer ipsum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nisl','lorem','926','euismod urna. Nullam lobortis quam a');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu','ligula.','1017','per conubia nostra, per inceptos hymenaeos. Mauris ut');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sem','enim.','814','lorem, auctor quis, tristique ac,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('amet','mi','784','arcu ac orci. Ut semper pretium neque. Morbi quis urna.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('risus','ligula','830','nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('augue','augue','810','tellus, imperdiet non,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('odio','faucibus.','655','hendrerit id, ante.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Phasellus','ipsum','1119','scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nec,','egestas.','892','Donec feugiat metus sit amet ante.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('velit.','risus.','1053','cubilia Curae; Donec tincidunt. Donec vitae erat vel pede');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('gravida','diam','953','sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('massa.','ipsum.','861','non enim. Mauris quis turpis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('neque','libero','636','Integer eu lacus. Quisque imperdiet, erat nonummy');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('est.','Aliquam','886','Donec vitae');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('euismod','tempor','947','urna et arcu imperdiet ullamcorper. Duis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nec','Nulla','663','ut, molestie in, tempus eu, ligula. Aenean euismod');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('magna.','amet','836','ornare, facilisis eget, ipsum. Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('imperdiet','tellus,','695','lectus convallis est,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Sed','nisi','994','metus. Vivamus euismod urna. Nullam lobortis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('interdum.','bibendum.','886','velit eu sem. Pellentesque ut ipsum ac mi');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Vestibulum','ligula.','891','orci.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('turpis','vulputate,','1012','vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('metus','dis','829','orci luctus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('magna','in','661','arcu et pede.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('cubilia','non,','633','vulputate, risus a ultricies adipiscing, enim mi tempor lorem,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mattis','ullamcorper','1107','semper egestas, urna');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ac,','Nullam','1014','ut');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('faucibus','a,','1008','velit eu sem.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lacus.','arcu.','665','enim, gravida sit amet, dapibus id, blandit at, nisi.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pellentesque','porttitor','1113','Aliquam ultrices iaculis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vitae','sem','1025','ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dictum','Nullam','705','molestie pharetra nibh. Aliquam ornare, libero at auctor');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('augue','vestibulum,','724','risus. In mi pede, nonummy ut, molestie in,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('faucibus','eu','1111','Quisque');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mi','vestibulum','1054','erat, in');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('iaculis,','ac','652','risus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('malesuada','nulla.','953','urna convallis erat, eget');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('porttitor','eu','910','luctus. Curabitur egestas nunc sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Donec','sit','873','nec, diam. Duis mi enim, condimentum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('condimentum','gravida','954','auctor odio a purus. Duis elementum, dui quis accumsan');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('id','nec','885','elit erat vitae risus. Duis a mi fringilla mi lacinia');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('non','pede','837','tempus mauris erat eget ipsum. Suspendisse');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('a,','lectus','805','Sed malesuada augue ut lacus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('amet','vel','713','sociis natoque penatibus et magnis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('diam','semper.','738','sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Maecenas','nunc,','1091','volutpat. Nulla dignissim.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('a,','ut','707','Nullam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('libero','tellus,','1027','eleifend');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sit','metus','741','sed consequat auctor, nunc nulla vulputate');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Nullam','elit,','969','at,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tempus','magna','636','sodales elit erat vitae');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mi','ipsum','982','ipsum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Aliquam','fringilla','805','luctus et ultrices posuere cubilia Curae; Donec tincidunt.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tortor','Maecenas','1024','dolor. Fusce mi lorem, vehicula');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Donec','rutrum','791','Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Nullam','nulla','811','urna, nec luctus felis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ipsum','eu','717','elementum, lorem ut aliquam iaculis,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('molestie','Donec','916','magna a tortor. Nunc commodo');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Phasellus','non,','1111','Donec tempor, est ac mattis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Etiam','libero.','961','nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nec','nibh','1103','pede. Praesent');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('consectetuer','in','1074','Fusce mi');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tincidunt','ac','769','vitae semper egestas,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('est','eget','690','eu, ultrices sit amet, risus. Donec nibh');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('a','elit,','708','diam. Duis mi enim, condimentum eget, volutpat ornare,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ligula.','Nullam','925','feugiat tellus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eget','magna','628','Donec egestas.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu,','ac','962','tellus justo sit amet nulla. Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('est.','non,','693','Nunc mauris.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tempus','erat','912','erat nonummy ultricies');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ac','Curabitur','754','magnis dis parturient montes, nascetur ridiculus mus. Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('libero.','nunc','1016','dignissim. Maecenas ornare egestas');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ac','Phasellus','990','eget, venenatis a, magna.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('cursus','Donec','700','arcu. Vestibulum ante ipsum primis in faucibus orci');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('id,','scelerisque','1103','tristique pellentesque, tellus sem');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('orci.','a','819','metus vitae velit egestas lacinia. Sed congue,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('arcu.','risus.','921','fermentum convallis ligula. Donec luctus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('auctor','In','1042','malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Praesent','elementum,','939','sapien. Cras dolor dolor, tempus non, lacinia at, iaculis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ultrices.','non','971','massa. Vestibulum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('in','lacinia','704','iaculis nec,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Cum','ligula','1080','elit.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('et,','non','807','pede. Cras vulputate velit eu sem. Pellentesque');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu','quis','642','imperdiet non, vestibulum nec,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('auctor.','sit','776','dui, in sodales elit erat vitae');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dapibus','pede','927','lectus pede, ultrices');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('inceptos','quam,','1118','ligula. Aenean euismod');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('fermentum','in,','1111','ipsum sodales purus, in molestie tortor nibh sit amet orci.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Donec','Phasellus','951','sed libero. Proin sed turpis nec mauris blandit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Vivamus','luctus','1004','ligula.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mus.','adipiscing','883','ornare');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Praesent','dui.','652','dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mattis.','erat','834','nec luctus felis purus ac tellus. Suspendisse sed dolor.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('in','posuere,','742','vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Aliquam','magna.','962','metus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('augue.','consequat','868','erat vitae risus. Duis a mi fringilla');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('cursus','velit.','687','ut cursus luctus, ipsum leo elementum sem, vitae aliquam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('est.','sapien.','844','senectus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lorem','fringilla','971','cursus et, magna. Praesent interdum ligula eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('non','Nam','737','orci sem eget massa. Suspendisse eleifend.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lobortis','turpis.','893','arcu et pede. Nunc sed orci lobortis augue');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pede,','lobortis','769','lorem, vehicula');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('massa','Mauris','750','est. Mauris eu turpis. Nulla');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Pellentesque','posuere','709','egestas.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('et','Suspendisse','828','Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sed,','tempor','1015','molestie tellus. Aenean egestas hendrerit neque.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dui','et','702','montes, nascetur');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tellus','Proin','1042','quis, pede. Suspendisse dui. Fusce diam nunc,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nulla','amet','716','diam dictum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('porta','justo','764','Mauris quis turpis vitae');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('augue','sem','976','Aliquam fringilla cursus purus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('consequat','Quisque','960','cubilia Curae; Phasellus ornare.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('aliquet','enim','939','malesuada fames ac turpis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('feugiat','ante','846','Vivamus non lorem vitae odio sagittis semper. Nam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('congue,','consectetuer','683','nisi. Aenean eget metus. In nec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('accumsan','rhoncus.','1097','feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dictum','eu','676','Vestibulum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('at,','Cum','1064','aliquet libero. Integer in magna. Phasellus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('aliquet','elit.','1033','molestie orci tincidunt adipiscing.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('placerat','eu','767','convallis, ante lectus convallis est, vitae sodales nisi magna');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('semper','malesuada','870','sed dui. Fusce aliquam,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('amet','consequat','799','scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Donec','commodo','890','non dui nec urna suscipit nonummy. Fusce fermentum fermentum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dignissim.','condimentum','966','arcu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ornare.','nec','705','Donec est. Nunc ullamcorper, velit in aliquet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('elit,','Aliquam','1040','ante, iaculis nec, eleifend non,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Nullam','quam.','740','sem');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('erat.','quis,','653','Sed id risus quis diam luctus lobortis. Class');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('euismod','eu','648','elit, pharetra ut, pharetra sed, hendrerit a,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sed,','adipiscing','1067','montes, nascetur ridiculus mus. Donec dignissim magna');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('orci','congue','827','felis. Donec tempor, est ac mattis semper,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('posuere,','dolor','1064','Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Praesent','sit','1054','Etiam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Maecenas','interdum','991','ac arcu.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Cras','Quisque','1060','Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nec','nulla','994','dictum eu, placerat eget, venenatis a, magna. Lorem ipsum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('quis','dictum','923','iaculis quis, pede. Praesent eu dui. Cum sociis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('at','ipsum.','1027','et, magna. Praesent interdum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('accumsan','Sed','664','ipsum. Donec sollicitudin adipiscing');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('In','In','888','tristique senectus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sodales','Pellentesque','688','amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('non','bibendum','821','pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('risus.','accumsan','853','eget ipsum. Suspendisse sagittis. Nullam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('risus.','imperdiet','1101','convallis erat, eget tincidunt dui');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('libero','at,','979','lacinia mattis. Integer eu lacus. Quisque imperdiet,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pellentesque','augue,','671','elit erat vitae risus. Duis a mi fringilla mi');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('est.','Duis','1079','dictum. Proin eget odio.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Donec','ac','685','tincidunt. Donec vitae erat vel');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vitae','ultrices.','628','cubilia Curae; Donec tincidunt. Donec vitae');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('massa.','scelerisque','741','rutrum urna, nec luctus felis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('volutpat','malesuada','1023','egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nulla','eu,','785','scelerisque dui.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nibh','Aliquam','663','sagittis lobortis mauris. Suspendisse aliquet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('natoque','nisi.','786','convallis erat, eget tincidunt dui augue eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ac','magnis','994','mi tempor lorem, eget mollis lectus pede');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sed','ac','1078','ridiculus mus. Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pharetra,','scelerisque','844','enim, sit amet ornare lectus justo eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nunc','Donec','847','metus. In nec orci. Donec nibh. Quisque nonummy ipsum non');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('est.','per','709','sit amet orci. Ut');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Morbi','pede.','900','metus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sociis','leo.','1023','nunc. Quisque ornare tortor at');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('diam.','vel,','759','ultrices. Duis volutpat nunc');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('felis.','enim.','812','vitae risus. Duis a');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ut','et','875','ut, sem. Nulla interdum.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mauris','fames','1071','magna. Praesent interdum ligula eu enim. Etiam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('diam.','Duis','810','volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu','cursus','692','Curabitur consequat, lectus sit amet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Praesent','accumsan','999','congue turpis. In condimentum. Donec at arcu. Vestibulum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mauris','mauris','1112','Cras vulputate velit eu sem. Pellentesque ut ipsum ac');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Cras','vel','1064','Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vulputate','tincidunt,','961','amet diam eu dolor egestas');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('egestas.','lorem,','698','Aenean eget metus. In');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('primis','adipiscing','829','dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('est.','est.','968','Curabitur ut odio vel');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sed','Nunc','676','in magna.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Vivamus','parturient','684','amet, consectetuer adipiscing elit.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu','lacus,','786','sollicitudin orci sem');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu,','tincidunt','969','eget metus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pede.','a','888','eu turpis.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('diam','erat','814','Integer mollis. Integer tincidunt aliquam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dolor.','tempus','858','vulputate eu,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mauris.','hendrerit','706','Curabitur ut odio vel est tempor');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('at,','sapien,','809','convallis erat, eget tincidunt dui augue eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('arcu.','vitae','688','lacus. Quisque');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ut','aliquet','807','Proin vel nisl. Quisque fringilla euismod enim. Etiam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ultrices','purus.','695','dapibus ligula. Aliquam erat volutpat. Nulla');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('in,','ac','793','ligula tortor, dictum eu, placerat eget,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Curabitur','Sed','639','vulputate mauris sagittis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tempor','ipsum','1092','Sed nunc');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ornare,','malesuada.','677','Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ac,','Phasellus','912','Nunc ac sem ut dolor dapibus gravida.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('velit.','feugiat','986','aliquet nec, imperdiet nec, leo.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('fermentum','Proin','870','pharetra, felis eget varius ultrices, mauris ipsum porta elit, a');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('placerat','taciti','1008','dui, in sodales elit erat');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vestibulum.','Etiam','891','Donec tincidunt. Donec vitae erat vel pede blandit congue.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('enim','dui','1109','orci, adipiscing non, luctus sit amet, faucibus ut, nulla.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vitae','Ut','817','vestibulum. Mauris magna. Duis dignissim tempor');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('volutpat','Donec','845','ridiculus mus. Proin vel arcu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('dui.','lorem','630','vehicula. Pellentesque tincidunt tempus risus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ipsum.','luctus','682','faucibus leo, in lobortis tellus justo sit amet nulla.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('rutrum','pede','670','lacinia orci, consectetuer euismod est arcu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lorem','lacus','896','ultricies dignissim lacus. Aliquam rutrum lorem ac');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Nunc','malesuada','976','Cras eget nisi dictum augue malesuada malesuada.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('et','condimentum.','1047','euismod enim. Etiam gravida molestie arcu. Sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lacinia','pede.','1071','Nunc sed orci lobortis augue scelerisque');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('libero','Integer','909','eleifend, nunc risus varius orci,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('semper,','in,','986','amet metus. Aliquam erat volutpat. Nulla facilisis.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Duis','rhoncus.','1102','dapibus quam quis diam. Pellentesque');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Phasellus','nec','1015','lacinia. Sed congue, elit sed consequat');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pharetra.','sed,','941','molestie dapibus ligula.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('velit','lacinia','1085','Sed nulla ante, iaculis nec, eleifend non,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('blandit','vulputate','979','odio. Phasellus at augue');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nec','Curabitur','752','Ut tincidunt orci quis lectus. Nullam suscipit, est');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('aliquet.','ornare','1081','quis lectus. Nullam suscipit,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sit','rhoncus','1074','quam a felis ullamcorper');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('gravida','vitae','751','in sodales elit erat vitae risus. Duis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Fusce','amet,','1015','in lobortis tellus justo sit amet nulla.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ipsum','arcu','648','erat. Vivamus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tincidunt','dignissim','863','Praesent eu dui. Cum sociis natoque penatibus et');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('orci,','per','958','mi eleifend egestas. Sed pharetra, felis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eget','auctor,','997','orci tincidunt adipiscing. Mauris molestie pharetra');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ligula.','mauris','1020','quis diam. Pellentesque habitant morbi');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sit','tincidunt,','638','sapien');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('magna.','ridiculus','948','egestas');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('elit.','non,','1110','neque sed dictum eleifend, nunc risus varius orci, in consequat');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ornare,','tempor','998','scelerisque neque sed sem egestas blandit. Nam nulla magna,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ultrices.','mus.','647','fermentum risus, at fringilla purus mauris a nunc.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Praesent','sem','822','pharetra');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ultricies','vitae','807','eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('fermentum','Aliquam','1117','semper rutrum. Fusce dolor quam, elementum at, egestas a,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('amet','aliquet','923','Cras');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('est,','lorem,','829','gravida.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('magnis','eu','1082','dictum placerat, augue. Sed molestie. Sed');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ipsum','leo.','1109','mollis lectus pede et risus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('amet,','suscipit','988','dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sed','ut','636','Nunc mauris. Morbi');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Nullam','vitae','634','ante');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lobortis','tincidunt','1028','mus. Aenean eget magna. Suspendisse tristique');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('rhoncus','amet,','1030','consectetuer euismod est arcu ac orci. Ut semper pretium neque.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('euismod','iaculis','1051','egestas');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tempus','aliquet','1007','metus eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nisl','magna.','1046','aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('convallis','enim.','808','non enim');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('In','eget','627','leo elementum sem, vitae aliquam eros turpis non enim. Mauris');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Nunc','et,','1107','faucibus orci luctus et ultrices posuere cubilia Curae; Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nonummy','at','800','Curabitur egestas nunc sed libero. Proin');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('commodo','Maecenas','1098','felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pede,','nec','695','dolor dolor, tempus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ante','rhoncus.','658','in magna. Phasellus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu,','diam','1096','Integer id magna et ipsum cursus vestibulum.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('odio','tincidunt','928','nisl. Quisque fringilla euismod enim. Etiam gravida');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nec,','mi','851','varius et, euismod et, commodo at,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pede.','ut,','849','scelerisque neque sed sem egestas blandit.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vulputate','ridiculus','849','eu tellus eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ligula.','id','1001','Curabitur consequat, lectus sit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Morbi','Suspendisse','994','Suspendisse sagittis. Nullam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('massa.','Fusce','849','ipsum primis in faucibus orci luctus et');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lacus.','eu','772','aliquam arcu. Aliquam ultrices iaculis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('suscipit','elit,','885','lectus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Aliquam','turpis.','1038','tristique pellentesque, tellus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('et','nunc,','1096','arcu eu odio tristique pharetra.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pharetra','a,','671','urna. Vivamus molestie dapibus ligula.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('molestie','dolor.','765','tincidunt dui augue eu');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sit','rhoncus','1015','pede. Cum sociis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Cras','justo.','938','sem magna');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nulla.','non,','708','id, mollis nec, cursus a, enim. Suspendisse');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Fusce','mollis','1027','Etiam laoreet, libero');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nibh','felis','708','eu augue porttitor interdum. Sed auctor odio');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('risus','diam.','901','odio vel est');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('facilisi.','Etiam','937','ac mattis semper, dui lectus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('aliquet,','lacinia','872','ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('magna','erat','807','et ultrices posuere cubilia Curae; Phasellus ornare.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('interdum','non','809','a, scelerisque sed, sapien. Nunc pulvinar arcu et');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tempor','gravida.','854','auctor non, feugiat nec, diam. Duis mi');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('accumsan','nisi','652','Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eu','sem,','676','Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('posuere','quis,','654','sit');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('interdum','dolor','983','Integer sem elit, pharetra');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('libero','Duis','1023','lectus. Nullam suscipit, est ac facilisis');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vitae,','dui','918','interdum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Donec','malesuada','769','dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sed','accumsan','1006','mauris id sapien. Cras dolor dolor, tempus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('purus.','ligula','793','Cum sociis natoque penatibus et magnis dis parturient');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('blandit','consectetuer','979','ipsum. Curabitur');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('tempus','Mauris','767','eget lacus. Mauris non dui nec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Lorem','ante','1074','at fringilla purus mauris a');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('venenatis','Vivamus','1112','semper rutrum. Fusce');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('eget,','gravida.','789','euismod in,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('orci.','mi','1049','ante dictum mi, ac mattis velit justo nec ante.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lorem','Vestibulum','1086','diam luctus lobortis. Class');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('interdum','Nulla','839','sodales purus, in molestie tortor');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('litora','tempor','754','dis parturient montes, nascetur ridiculus mus. Proin');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pede,','lorem,','862','sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('magna','rhoncus.','729','vestibulum massa rutrum');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('iaculis','Aliquam','784','lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('vel,','ornare,','688','orci, adipiscing non,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('urna.','dolor','982','luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('sit','Nunc','1025','ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('id,','id','673','Maecenas ornare egestas ligula.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('mattis.','libero','627','tellus faucibus leo, in');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pretium','Duis','923','arcu. Curabitur ut odio vel est tempor bibendum. Donec');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('ut','eleifend.','636','quam quis diam. Pellentesque habitant morbi tristique senectus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('risus,','ipsum','1072','libero et tristique pellentesque, tellus sem mollis dui, in');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pulvinar','nec','711','at, libero. Morbi');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('egestas.','consequat','652','egestas lacinia. Sed congue, elit sed consequat auctor,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('lacus,','dui.','745','ac risus. Morbi metus. Vivamus euismod urna. Nullam');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('accumsan','Proin','977','dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('purus,','ac','999','massa. Vestibulum accumsan neque et nunc.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nascetur','Donec','690','tortor, dictum eu, placerat eget, venenatis a, magna. Lorem');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('amet','ipsum','808','metus. In lorem.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('Cras','libero','1120','gravida');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('adipiscing,','ut','1074','per inceptos hymenaeos. Mauris ut quam vel');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('semper','dui.','895','a, aliquet vel, vulputate eu,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nonummy','faucibus','896','ipsum. Phasellus vitae mauris sit amet lorem semper');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('adipiscing,','Fusce','795','sit amet massa.');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('semper','sit','1031','congue a, aliquet vel, vulputate eu,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('euismod','lorem.','752','lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('pellentesque','sollicitudin','631','mi. Duis risus');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('egestas','et','711','fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor,');
INSERT INTO skupina (nazev,hesloProPridani,idVedouciho,popis) VALUES ('nascetur','luctus','829','at');
