--------------------------------------------------------
--  File created - Støeda-bøezen-27-2013   
--------------------------------------------------------
REM INSERTING into DUPALPE1.SKUPINA
SET DEFINE OFF;
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('471','interdum','Nulla','839','sodales purus, in molestie tortor');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('472','litora','tempor','754','dis parturient montes, nascetur ridiculus mus. Proin');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('473','pede,','lorem,','862','sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('474','magna','rhoncus.','729','vestibulum massa rutrum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('475','iaculis','Aliquam','784','lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('476','vel,','ornare,','688','orci, adipiscing non,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('477','urna.','dolor','982','luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('478','sit','Nunc','1025','ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('479','id,','id','673','Maecenas ornare egestas ligula.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('480','mattis.','libero','627','tellus faucibus leo, in');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('481','pretium','Duis','923','arcu. Curabitur ut odio vel est tempor bibendum. Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('482','ut','eleifend.','636','quam quis diam. Pellentesque habitant morbi tristique senectus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('483','risus,','ipsum','1072','libero et tristique pellentesque, tellus sem mollis dui, in');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('484','pulvinar','nec','711','at, libero. Morbi');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('485','egestas.','consequat','652','egestas lacinia. Sed congue, elit sed consequat auctor,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('486','lacus,','dui.','745','ac risus. Morbi metus. Vivamus euismod urna. Nullam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('487','accumsan','Proin','977','dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('488','purus,','ac','999','massa. Vestibulum accumsan neque et nunc.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('489','nascetur','Donec','690','tortor, dictum eu, placerat eget, venenatis a, magna. Lorem');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('490','amet','ipsum','808','metus. In lorem.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('491','Cras','libero','1120','gravida');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('492','adipiscing,','ut','1074','per inceptos hymenaeos. Mauris ut quam vel');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('493','semper','dui.','895','a, aliquet vel, vulputate eu,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('494','nonummy','faucibus','896','ipsum. Phasellus vitae mauris sit amet lorem semper');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('495','adipiscing,','Fusce','795','sit amet massa.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('496','semper','sit','1031','congue a, aliquet vel, vulputate eu,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('497','euismod','lorem.','752','lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('498','pellentesque','sollicitudin','631','mi. Duis risus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('499','egestas','et','711','fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('500','nascetur','luctus','829','at');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('1','tellus','pretium','936','pharetra, felis eget');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('2','nec','dignissim','654','vel,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('3','dolor.','aliquet,','932','ut ipsum ac mi eleifend egestas. Sed pharetra,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('4','Vestibulum','Phasellus','665','scelerisque neque sed sem');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('5','parturient','mattis.','856','sed,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('6','vel','diam','919','Fusce diam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('7','ut','dolor,','1113','dapibus quam quis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('8','Proin','parturient','1091','Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('9','mi','ultrices,','676','Aliquam fringilla cursus purus. Nullam scelerisque neque sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('10','Donec','molestie','852','sapien. Aenean massa. Integer vitae');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('11','luctus','tincidunt,','735','Nullam ut nisi a odio semper cursus. Integer mollis.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('12','erat','sapien','792','faucibus ut, nulla. Cras eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('13','Cras','tellus','685','mi. Aliquam gravida mauris ut mi. Duis risus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('14','mi.','pellentesque','1061','fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('15','massa.','dui,','1120','Phasellus nulla. Integer vulputate, risus a ultricies');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('16','quam','vel','665','Sed auctor odio a purus. Duis elementum, dui');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('17','cubilia','eget','1014','ante bibendum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('18','sem','auctor','704','et, eros. Proin ultrices. Duis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('19','natoque','luctus,','825','ac mattis velit justo nec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('20','penatibus','facilisis','925','augue eu tellus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('21','Sed','ipsum','774','Curabitur dictum. Phasellus in felis. Nulla tempor augue');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('22','magnis','dictum','747','nisi. Mauris nulla. Integer urna. Vivamus molestie');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('23','Integer','dictum','788','mauris id sapien. Cras dolor dolor,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('24','Donec','nec,','1111','Cum sociis natoque penatibus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('25','dolor','nisi','1068','at sem molestie sodales.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('26','sociosqu','nibh','676','non sapien molestie');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('27','eu','Proin','984','non');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('28','Pellentesque','Mauris','822','purus ac tellus. Suspendisse sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('29','lacus.','quam','777','nec, imperdiet nec,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('30','dictum','aliquet','900','nunc risus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('31','a','Nulla','816','Vestibulum ante');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('32','Donec','ornare','1002','fringilla');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('33','adipiscing','nec','1072','velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('34','Integer','ut,','735','lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('35','fames','auctor','678','lobortis. Class aptent taciti sociosqu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('36','orci,','tellus.','998','Phasellus libero mauris, aliquam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('37','varius','amet','820','Aliquam ultrices iaculis odio.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('38','gravida','imperdiet','727','eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('39','Curae;','aliquet,','1087','et ultrices posuere cubilia Curae;');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('40','id','lacus.','766','luctus felis purus ac tellus. Suspendisse sed dolor. Fusce');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('41','dui,','quam.','722','diam. Proin dolor. Nulla');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('42','Integer','turpis.','1109','amet luctus vulputate, nisi sem semper erat, in consectetuer');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('43','Nunc','diam.','1013','Nunc pulvinar arcu et');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('44','tellus','Nam','823','Curabitur ut odio vel');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('45','a,','Fusce','1032','magnis dis parturient montes, nascetur ridiculus mus. Aenean');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('46','Aliquam','rutrum','1025','iaculis enim, sit amet ornare lectus justo eu arcu. Morbi');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('47','ipsum','at','847','rhoncus. Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('48','Ut','Suspendisse','964','interdum ligula eu enim. Etiam imperdiet dictum magna.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('49','Aliquam','consectetuer','824','egestas. Sed pharetra, felis eget varius');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('50','quis','aliquam','1123','non, hendrerit id, ante. Nunc mauris sapien, cursus in,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('51','turpis.','purus.','956','dui, nec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('52','sociis','molestie.','685','eget, venenatis a, magna. Lorem ipsum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('53','sed','tellus.','664','lacus vestibulum lorem, sit amet ultricies sem magna');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('54','purus','Donec','795','habitant morbi tristique senectus et netus et');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('55','augue.','dictum','807','urna convallis erat, eget');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('56','enim,','tellus.','1062','a');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('57','rutrum.','odio','809','sapien. Cras dolor dolor, tempus non, lacinia');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('58','ante','ultrices','947','In ornare sagittis felis. Donec tempor, est ac mattis semper,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('59','Quisque','magna.','835','sed, facilisis vitae, orci. Phasellus dapibus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('60','consectetuer','nibh','1045','Nam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('61','eget','pede.','774','Curabitur consequat, lectus sit amet luctus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('62','Duis','Aliquam','801','Proin vel arcu eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('63','aliquet','nibh','825','malesuada. Integer id');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('64','arcu.','egestas.','912','erat eget');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('65','ipsum','Nam','996','Aliquam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('66','ornare','tempus','639','enim,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('67','Ut','leo,','885','ullamcorper, nisl arcu iaculis enim, sit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('68','volutpat.','nibh.','956','Cum sociis natoque penatibus et');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('69','venenatis','sapien','1074','Proin nisl sem, consequat nec, mollis vitae, posuere');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('70','nunc.','purus,','809','elit, pharetra ut, pharetra sed, hendrerit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('71','ac','pellentesque.','673','at augue id ante dictum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('72','risus.','interdum','990','mi, ac mattis velit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('73','turpis','lacus.','763','non ante bibendum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('74','malesuada','Praesent','830','amet diam eu dolor egestas rhoncus. Proin nisl sem,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('75','tempus','nunc.','1043','imperdiet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('76','ornare,','aliquet','964','odio. Phasellus at augue id ante dictum cursus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('77','purus.','Nunc','748','erat volutpat. Nulla dignissim. Maecenas ornare');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('78','non,','erat','902','nec, euismod in,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('79','posuere','metus','997','amet lorem semper');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('80','et','orci','805','diam vel arcu. Curabitur ut odio vel');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('81','fringilla,','eget','758','est ac facilisis facilisis, magna tellus faucibus leo, in');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('82','vitae','vulputate,','958','nulla. In tincidunt congue turpis.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('83','dictum','dictum','889','vulputate,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('84','mus.','blandit','760','vulputate ullamcorper magna.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('85','ac,','ac','862','natoque penatibus et magnis dis parturient');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('86','vehicula','nibh','973','dui');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('87','erat','in,','708','magna tellus faucibus leo, in lobortis tellus justo');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('88','Cras','Quisque','893','sit amet ultricies sem magna nec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('89','Vivamus','mi,','726','orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('90','Pellentesque','quam','752','ipsum non');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('91','ipsum.','egestas','671','iaculis enim, sit amet ornare lectus justo eu arcu.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('92','eu','volutpat.','799','Suspendisse aliquet, sem ut cursus luctus,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('93','aliquam','pede','800','blandit viverra. Donec tempus, lorem fringilla ornare');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('94','eu,','dignissim','1122','erat. Etiam vestibulum massa rutrum magna. Cras');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('95','turpis','ipsum','975','elit,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('96','Vivamus','Nunc','1051','felis orci,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('97','nunc','lorem','966','ipsum nunc id enim. Curabitur massa. Vestibulum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('98','posuere,','nisl','644','velit egestas lacinia.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('99','sem.','Nunc','947','convallis, ante lectus convallis est, vitae sodales nisi magna sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('100','at','parturient','1036','ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('101','elementum','lacus.','1091','vitae semper egestas, urna justo faucibus lectus, a');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('102','enim','vel','1032','Nullam velit dui,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('103','ac','ipsum','838','ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('104','vel','cursus','1009','Praesent eu nulla at sem molestie');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('105','aliquam,','lobortis','969','odio');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('106','ipsum.','purus.','683','mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('107','risus.','gravida.','834','magna, malesuada vel, convallis in, cursus et, eros.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('108','Nullam','dui','699','sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('109','nibh.','molestie.','1096','tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('110','quis','enim,','872','enim, condimentum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('111','sapien','Duis','1017','pellentesque. Sed dictum. Proin eget');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('112','quis,','vitae','831','Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('113','orci','iaculis','687','Nullam ut nisi a odio');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('114','Phasellus','velit','706','a, arcu.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('115','adipiscing','nisi','1059','ac nulla. In tincidunt congue turpis.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('116','elementum','dolor','740','pretium aliquet, metus urna convallis erat, eget');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('117','a','Phasellus','754','posuere vulputate, lacus. Cras interdum.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('118','torquent','magna','760','eu erat semper rutrum. Fusce dolor');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('119','ultricies','condimentum.','1049','eget');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('120','Sed','ultrices','1047','mattis semper,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('121','Aliquam','magna.','967','mus. Proin vel arcu eu odio');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('122','ut','dictum','861','Donec felis orci, adipiscing non, luctus sit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('123','aliquet','mollis.','747','pede. Cras vulputate velit eu sem. Pellentesque ut ipsum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('124','sem','dolor','694','a, arcu. Sed et libero.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('125','id','purus.','886','non nisi. Aenean');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('126','urna','tempor','672','dui. Cum sociis natoque penatibus et magnis dis parturient');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('127','fermentum','lectus','670','urna justo faucibus lectus, a');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('128','dui','arcu.','819','ullamcorper. Duis at lacus. Quisque');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('129','magna.','nunc','785','adipiscing elit. Curabitur sed tortor.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('130','nec,','dui.','1113','Praesent interdum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('131','eu','metus.','1064','augue id ante dictum cursus. Nunc mauris elit,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('132','bibendum','Mauris','804','magna. Phasellus dolor');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('133','Lorem','eros','866','eu metus. In lorem. Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('134','pede,','molestie','1085','ipsum. Phasellus vitae mauris sit amet lorem semper');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('135','augue','et','1021','orci. Ut semper');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('136','orci','metus.','931','mattis velit justo nec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('137','pede,','lorem','796','ac libero nec ligula consectetuer');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('138','iaculis','eu','743','mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('139','ac','tristique','1055','bibendum. Donec felis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('140','vel','sociosqu','727','pede. Cras vulputate');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('141','Praesent','erat.','1006','feugiat nec, diam. Duis mi enim, condimentum eget,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('142','metus.','libero.','829','ultrices');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('143','placerat','est','662','Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('144','facilisis','lorem,','735','sit amet lorem semper auctor. Mauris vel turpis. Aliquam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('145','Cras','sem','970','nunc ac mattis ornare, lectus ante dictum mi, ac');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('146','volutpat','varius','1118','Donec fringilla. Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('147','semper','metus.','740','semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('148','Aenean','et','961','lorem ac risus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('149','convallis','Sed','715','eu, odio. Phasellus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('150','et','mi','660','arcu iaculis enim,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('151','a,','tempor','1071','penatibus et magnis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('152','nibh','elit,','1016','eget, venenatis a, magna. Lorem');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('153','massa.','ligula','709','mollis. Duis sit amet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('154','Maecenas','nibh','1005','a, arcu. Sed et libero. Proin mi. Aliquam gravida');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('155','mi,','Duis','638','velit dui, semper et,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('156','molestie','felis','947','est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('157','odio.','natoque','903','odio. Aliquam vulputate ullamcorper magna. Sed eu eros.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('158','justo.','ut,','800','aliquet. Proin velit. Sed malesuada augue ut');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('159','urna','ante','657','nec mauris blandit mattis.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('160','Duis','in','1058','Donec dignissim magna');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('161','enim','turpis.','1092','risus. In mi pede, nonummy');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('162','Aliquam','scelerisque','679','eros nec tellus. Nunc lectus pede, ultrices a, auctor');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('163','nisi.','mauris','1109','eu dolor egestas');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('164','gravida','at,','998','mollis. Duis sit amet diam eu dolor egestas rhoncus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('165','tempus,','metus.','884','molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('166','purus.','Maecenas','1071','morbi tristique senectus et netus et');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('167','facilisi.','In','709','neque');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('168','tellus','parturient','775','amet ornare lectus justo eu arcu. Morbi sit amet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('169','ante','Aliquam','791','neque');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('170','tincidunt','magna','880','cursus. Nunc mauris elit,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('171','egestas,','in,','728','malesuada id, erat. Etiam vestibulum massa rutrum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('172','pede','purus','683','vitae sodales nisi magna');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('173','nascetur','vel','1077','in faucibus orci luctus et ultrices posuere');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('174','lectus','amet','747','neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('175','molestie','interdum','733','mauris sit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('176','Ut','lacinia','987','adipiscing elit. Aliquam auctor, velit eget laoreet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('177','tristique','vestibulum.','872','Proin mi. Aliquam gravida mauris');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('178','Mauris','Nam','661','Integer id magna et ipsum cursus vestibulum.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('179','sit','euismod','888','a');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('180','feugiat.','ac','794','semper erat, in consectetuer ipsum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('181','nisl','lorem','926','euismod urna. Nullam lobortis quam a');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('182','eu','ligula.','1017','per conubia nostra, per inceptos hymenaeos. Mauris ut');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('183','sem','enim.','814','lorem, auctor quis, tristique ac,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('184','amet','mi','784','arcu ac orci. Ut semper pretium neque. Morbi quis urna.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('185','risus','ligula','830','nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('186','augue','augue','810','tellus, imperdiet non,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('187','odio','faucibus.','655','hendrerit id, ante.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('188','Phasellus','ipsum','1119','scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('189','nec,','egestas.','892','Donec feugiat metus sit amet ante.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('190','velit.','risus.','1053','cubilia Curae; Donec tincidunt. Donec vitae erat vel pede');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('191','gravida','diam','953','sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('192','massa.','ipsum.','861','non enim. Mauris quis turpis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('193','neque','libero','636','Integer eu lacus. Quisque imperdiet, erat nonummy');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('194','est.','Aliquam','886','Donec vitae');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('195','euismod','tempor','947','urna et arcu imperdiet ullamcorper. Duis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('196','nec','Nulla','663','ut, molestie in, tempus eu, ligula. Aenean euismod');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('197','magna.','amet','836','ornare, facilisis eget, ipsum. Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('198','imperdiet','tellus,','695','lectus convallis est,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('199','Sed','nisi','994','metus. Vivamus euismod urna. Nullam lobortis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('200','interdum.','bibendum.','886','velit eu sem. Pellentesque ut ipsum ac mi');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('201','Vestibulum','ligula.','891','orci.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('202','turpis','vulputate,','1012','vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('203','metus','dis','829','orci luctus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('204','magna','in','661','arcu et pede.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('205','cubilia','non,','633','vulputate, risus a ultricies adipiscing, enim mi tempor lorem,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('206','mattis','ullamcorper','1107','semper egestas, urna');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('207','ac,','Nullam','1014','ut');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('208','faucibus','a,','1008','velit eu sem.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('209','lacus.','arcu.','665','enim, gravida sit amet, dapibus id, blandit at, nisi.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('210','pellentesque','porttitor','1113','Aliquam ultrices iaculis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('211','vitae','sem','1025','ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('212','dictum','Nullam','705','molestie pharetra nibh. Aliquam ornare, libero at auctor');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('213','augue','vestibulum,','724','risus. In mi pede, nonummy ut, molestie in,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('214','faucibus','eu','1111','Quisque');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('215','mi','vestibulum','1054','erat, in');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('216','iaculis,','ac','652','risus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('217','malesuada','nulla.','953','urna convallis erat, eget');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('218','porttitor','eu','910','luctus. Curabitur egestas nunc sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('219','Donec','sit','873','nec, diam. Duis mi enim, condimentum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('220','condimentum','gravida','954','auctor odio a purus. Duis elementum, dui quis accumsan');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('221','id','nec','885','elit erat vitae risus. Duis a mi fringilla mi lacinia');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('222','non','pede','837','tempus mauris erat eget ipsum. Suspendisse');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('223','a,','lectus','805','Sed malesuada augue ut lacus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('224','amet','vel','713','sociis natoque penatibus et magnis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('225','diam','semper.','738','sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('226','Maecenas','nunc,','1091','volutpat. Nulla dignissim.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('227','a,','ut','707','Nullam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('228','libero','tellus,','1027','eleifend');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('229','sit','metus','741','sed consequat auctor, nunc nulla vulputate');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('230','Nullam','elit,','969','at,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('231','tempus','magna','636','sodales elit erat vitae');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('232','mi','ipsum','982','ipsum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('233','Aliquam','fringilla','805','luctus et ultrices posuere cubilia Curae; Donec tincidunt.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('234','tortor','Maecenas','1024','dolor. Fusce mi lorem, vehicula');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('235','Donec','rutrum','791','Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('236','Nullam','nulla','811','urna, nec luctus felis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('237','ipsum','eu','717','elementum, lorem ut aliquam iaculis,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('238','molestie','Donec','916','magna a tortor. Nunc commodo');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('239','Phasellus','non,','1111','Donec tempor, est ac mattis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('240','Etiam','libero.','961','nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('241','nec','nibh','1103','pede. Praesent');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('242','consectetuer','in','1074','Fusce mi');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('243','tincidunt','ac','769','vitae semper egestas,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('244','est','eget','690','eu, ultrices sit amet, risus. Donec nibh');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('245','a','elit,','708','diam. Duis mi enim, condimentum eget, volutpat ornare,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('246','ligula.','Nullam','925','feugiat tellus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('247','eget','magna','628','Donec egestas.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('248','eu,','ac','962','tellus justo sit amet nulla. Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('249','est.','non,','693','Nunc mauris.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('250','tempus','erat','912','erat nonummy ultricies');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('251','ac','Curabitur','754','magnis dis parturient montes, nascetur ridiculus mus. Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('252','libero.','nunc','1016','dignissim. Maecenas ornare egestas');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('253','ac','Phasellus','990','eget, venenatis a, magna.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('254','cursus','Donec','700','arcu. Vestibulum ante ipsum primis in faucibus orci');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('255','id,','scelerisque','1103','tristique pellentesque, tellus sem');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('256','orci.','a','819','metus vitae velit egestas lacinia. Sed congue,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('257','arcu.','risus.','921','fermentum convallis ligula. Donec luctus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('258','auctor','In','1042','malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('259','Praesent','elementum,','939','sapien. Cras dolor dolor, tempus non, lacinia at, iaculis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('260','ultrices.','non','971','massa. Vestibulum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('261','in','lacinia','704','iaculis nec,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('262','Cum','ligula','1080','elit.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('263','et,','non','807','pede. Cras vulputate velit eu sem. Pellentesque');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('264','eu','quis','642','imperdiet non, vestibulum nec,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('265','auctor.','sit','776','dui, in sodales elit erat vitae');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('266','dapibus','pede','927','lectus pede, ultrices');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('267','inceptos','quam,','1118','ligula. Aenean euismod');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('268','fermentum','in,','1111','ipsum sodales purus, in molestie tortor nibh sit amet orci.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('269','Donec','Phasellus','951','sed libero. Proin sed turpis nec mauris blandit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('270','Vivamus','luctus','1004','ligula.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('271','mus.','adipiscing','883','ornare');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('272','Praesent','dui.','652','dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('273','mattis.','erat','834','nec luctus felis purus ac tellus. Suspendisse sed dolor.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('274','in','posuere,','742','vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('275','Aliquam','magna.','962','metus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('276','augue.','consequat','868','erat vitae risus. Duis a mi fringilla');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('277','cursus','velit.','687','ut cursus luctus, ipsum leo elementum sem, vitae aliquam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('278','est.','sapien.','844','senectus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('279','lorem','fringilla','971','cursus et, magna. Praesent interdum ligula eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('280','non','Nam','737','orci sem eget massa. Suspendisse eleifend.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('281','lobortis','turpis.','893','arcu et pede. Nunc sed orci lobortis augue');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('282','pede,','lobortis','769','lorem, vehicula');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('283','massa','Mauris','750','est. Mauris eu turpis. Nulla');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('284','Pellentesque','posuere','709','egestas.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('285','et','Suspendisse','828','Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('286','sed,','tempor','1015','molestie tellus. Aenean egestas hendrerit neque.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('287','dui','et','702','montes, nascetur');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('288','tellus','Proin','1042','quis, pede. Suspendisse dui. Fusce diam nunc,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('289','nulla','amet','716','diam dictum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('290','porta','justo','764','Mauris quis turpis vitae');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('291','augue','sem','976','Aliquam fringilla cursus purus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('292','consequat','Quisque','960','cubilia Curae; Phasellus ornare.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('293','aliquet','enim','939','malesuada fames ac turpis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('294','feugiat','ante','846','Vivamus non lorem vitae odio sagittis semper. Nam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('295','congue,','consectetuer','683','nisi. Aenean eget metus. In nec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('296','accumsan','rhoncus.','1097','feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('297','dictum','eu','676','Vestibulum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('298','at,','Cum','1064','aliquet libero. Integer in magna. Phasellus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('299','aliquet','elit.','1033','molestie orci tincidunt adipiscing.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('300','placerat','eu','767','convallis, ante lectus convallis est, vitae sodales nisi magna');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('301','semper','malesuada','870','sed dui. Fusce aliquam,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('302','amet','consequat','799','scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('303','Donec','commodo','890','non dui nec urna suscipit nonummy. Fusce fermentum fermentum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('304','dignissim.','condimentum','966','arcu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('305','ornare.','nec','705','Donec est. Nunc ullamcorper, velit in aliquet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('306','elit,','Aliquam','1040','ante, iaculis nec, eleifend non,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('307','Nullam','quam.','740','sem');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('308','erat.','quis,','653','Sed id risus quis diam luctus lobortis. Class');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('309','euismod','eu','648','elit, pharetra ut, pharetra sed, hendrerit a,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('310','sed,','adipiscing','1067','montes, nascetur ridiculus mus. Donec dignissim magna');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('311','orci','congue','827','felis. Donec tempor, est ac mattis semper,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('312','posuere,','dolor','1064','Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('313','Praesent','sit','1054','Etiam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('314','Maecenas','interdum','991','ac arcu.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('315','Cras','Quisque','1060','Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('316','nec','nulla','994','dictum eu, placerat eget, venenatis a, magna. Lorem ipsum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('317','quis','dictum','923','iaculis quis, pede. Praesent eu dui. Cum sociis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('318','at','ipsum.','1027','et, magna. Praesent interdum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('319','accumsan','Sed','664','ipsum. Donec sollicitudin adipiscing');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('320','In','In','888','tristique senectus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('321','sodales','Pellentesque','688','amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('322','non','bibendum','821','pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('323','risus.','accumsan','853','eget ipsum. Suspendisse sagittis. Nullam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('324','risus.','imperdiet','1101','convallis erat, eget tincidunt dui');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('325','libero','at,','979','lacinia mattis. Integer eu lacus. Quisque imperdiet,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('326','pellentesque','augue,','671','elit erat vitae risus. Duis a mi fringilla mi');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('327','est.','Duis','1079','dictum. Proin eget odio.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('328','Donec','ac','685','tincidunt. Donec vitae erat vel');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('329','vitae','ultrices.','628','cubilia Curae; Donec tincidunt. Donec vitae');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('330','massa.','scelerisque','741','rutrum urna, nec luctus felis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('331','volutpat','malesuada','1023','egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('332','nulla','eu,','785','scelerisque dui.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('333','nibh','Aliquam','663','sagittis lobortis mauris. Suspendisse aliquet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('334','natoque','nisi.','786','convallis erat, eget tincidunt dui augue eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('335','ac','magnis','994','mi tempor lorem, eget mollis lectus pede');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('336','sed','ac','1078','ridiculus mus. Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('337','pharetra,','scelerisque','844','enim, sit amet ornare lectus justo eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('338','nunc','Donec','847','metus. In nec orci. Donec nibh. Quisque nonummy ipsum non');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('339','est.','per','709','sit amet orci. Ut');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('340','Morbi','pede.','900','metus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('341','sociis','leo.','1023','nunc. Quisque ornare tortor at');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('342','diam.','vel,','759','ultrices. Duis volutpat nunc');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('343','felis.','enim.','812','vitae risus. Duis a');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('344','ut','et','875','ut, sem. Nulla interdum.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('345','mauris','fames','1071','magna. Praesent interdum ligula eu enim. Etiam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('346','diam.','Duis','810','volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('347','eu','cursus','692','Curabitur consequat, lectus sit amet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('348','Praesent','accumsan','999','congue turpis. In condimentum. Donec at arcu. Vestibulum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('349','mauris','mauris','1112','Cras vulputate velit eu sem. Pellentesque ut ipsum ac');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('350','Cras','vel','1064','Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('351','vulputate','tincidunt,','961','amet diam eu dolor egestas');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('352','egestas.','lorem,','698','Aenean eget metus. In');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('353','primis','adipiscing','829','dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('354','est.','est.','968','Curabitur ut odio vel');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('355','sed','Nunc','676','in magna.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('356','Vivamus','parturient','684','amet, consectetuer adipiscing elit.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('357','eu','lacus,','786','sollicitudin orci sem');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('358','eu,','tincidunt','969','eget metus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('359','pede.','a','888','eu turpis.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('360','diam','erat','814','Integer mollis. Integer tincidunt aliquam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('361','dolor.','tempus','858','vulputate eu,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('362','mauris.','hendrerit','706','Curabitur ut odio vel est tempor');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('363','at,','sapien,','809','convallis erat, eget tincidunt dui augue eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('364','arcu.','vitae','688','lacus. Quisque');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('365','ut','aliquet','807','Proin vel nisl. Quisque fringilla euismod enim. Etiam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('366','ultrices','purus.','695','dapibus ligula. Aliquam erat volutpat. Nulla');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('367','in,','ac','793','ligula tortor, dictum eu, placerat eget,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('368','Curabitur','Sed','639','vulputate mauris sagittis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('369','tempor','ipsum','1092','Sed nunc');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('370','ornare,','malesuada.','677','Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('371','ac,','Phasellus','912','Nunc ac sem ut dolor dapibus gravida.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('372','velit.','feugiat','986','aliquet nec, imperdiet nec, leo.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('373','fermentum','Proin','870','pharetra, felis eget varius ultrices, mauris ipsum porta elit, a');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('374','placerat','taciti','1008','dui, in sodales elit erat');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('375','vestibulum.','Etiam','891','Donec tincidunt. Donec vitae erat vel pede blandit congue.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('376','enim','dui','1109','orci, adipiscing non, luctus sit amet, faucibus ut, nulla.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('377','vitae','Ut','817','vestibulum. Mauris magna. Duis dignissim tempor');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('378','volutpat','Donec','845','ridiculus mus. Proin vel arcu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('379','dui.','lorem','630','vehicula. Pellentesque tincidunt tempus risus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('380','ipsum.','luctus','682','faucibus leo, in lobortis tellus justo sit amet nulla.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('381','rutrum','pede','670','lacinia orci, consectetuer euismod est arcu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('382','lorem','lacus','896','ultricies dignissim lacus. Aliquam rutrum lorem ac');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('383','Nunc','malesuada','976','Cras eget nisi dictum augue malesuada malesuada.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('384','et','condimentum.','1047','euismod enim. Etiam gravida molestie arcu. Sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('385','lacinia','pede.','1071','Nunc sed orci lobortis augue scelerisque');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('386','libero','Integer','909','eleifend, nunc risus varius orci,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('387','semper,','in,','986','amet metus. Aliquam erat volutpat. Nulla facilisis.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('388','Duis','rhoncus.','1102','dapibus quam quis diam. Pellentesque');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('389','Phasellus','nec','1015','lacinia. Sed congue, elit sed consequat');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('390','pharetra.','sed,','941','molestie dapibus ligula.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('391','velit','lacinia','1085','Sed nulla ante, iaculis nec, eleifend non,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('392','blandit','vulputate','979','odio. Phasellus at augue');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('393','nec','Curabitur','752','Ut tincidunt orci quis lectus. Nullam suscipit, est');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('394','aliquet.','ornare','1081','quis lectus. Nullam suscipit,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('395','sit','rhoncus','1074','quam a felis ullamcorper');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('396','gravida','vitae','751','in sodales elit erat vitae risus. Duis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('397','Fusce','amet,','1015','in lobortis tellus justo sit amet nulla.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('398','ipsum','arcu','648','erat. Vivamus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('399','tincidunt','dignissim','863','Praesent eu dui. Cum sociis natoque penatibus et');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('400','orci,','per','958','mi eleifend egestas. Sed pharetra, felis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('401','eget','auctor,','997','orci tincidunt adipiscing. Mauris molestie pharetra');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('402','ligula.','mauris','1020','quis diam. Pellentesque habitant morbi');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('403','sit','tincidunt,','638','sapien');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('404','magna.','ridiculus','948','egestas');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('405','elit.','non,','1110','neque sed dictum eleifend, nunc risus varius orci, in consequat');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('406','ornare,','tempor','998','scelerisque neque sed sem egestas blandit. Nam nulla magna,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('407','ultrices.','mus.','647','fermentum risus, at fringilla purus mauris a nunc.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('408','Praesent','sem','822','pharetra');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('409','ultricies','vitae','807','eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('410','fermentum','Aliquam','1117','semper rutrum. Fusce dolor quam, elementum at, egestas a,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('411','amet','aliquet','923','Cras');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('412','est,','lorem,','829','gravida.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('413','magnis','eu','1082','dictum placerat, augue. Sed molestie. Sed');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('414','ipsum','leo.','1109','mollis lectus pede et risus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('415','amet,','suscipit','988','dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('416','sed','ut','636','Nunc mauris. Morbi');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('417','Nullam','vitae','634','ante');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('418','lobortis','tincidunt','1028','mus. Aenean eget magna. Suspendisse tristique');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('419','rhoncus','amet,','1030','consectetuer euismod est arcu ac orci. Ut semper pretium neque.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('420','euismod','iaculis','1051','egestas');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('421','tempus','aliquet','1007','metus eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('422','nisl','magna.','1046','aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('423','convallis','enim.','808','non enim');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('424','In','eget','627','leo elementum sem, vitae aliquam eros turpis non enim. Mauris');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('425','Nunc','et,','1107','faucibus orci luctus et ultrices posuere cubilia Curae; Donec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('426','nonummy','at','800','Curabitur egestas nunc sed libero. Proin');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('427','commodo','Maecenas','1098','felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('428','pede,','nec','695','dolor dolor, tempus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('429','ante','rhoncus.','658','in magna. Phasellus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('430','eu,','diam','1096','Integer id magna et ipsum cursus vestibulum.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('431','odio','tincidunt','928','nisl. Quisque fringilla euismod enim. Etiam gravida');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('432','nec,','mi','851','varius et, euismod et, commodo at,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('433','pede.','ut,','849','scelerisque neque sed sem egestas blandit.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('434','vulputate','ridiculus','849','eu tellus eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('435','ligula.','id','1001','Curabitur consequat, lectus sit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('436','Morbi','Suspendisse','994','Suspendisse sagittis. Nullam');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('437','massa.','Fusce','849','ipsum primis in faucibus orci luctus et');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('438','lacus.','eu','772','aliquam arcu. Aliquam ultrices iaculis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('439','suscipit','elit,','885','lectus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('440','Aliquam','turpis.','1038','tristique pellentesque, tellus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('441','et','nunc,','1096','arcu eu odio tristique pharetra.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('442','pharetra','a,','671','urna. Vivamus molestie dapibus ligula.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('443','molestie','dolor.','765','tincidunt dui augue eu');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('444','sit','rhoncus','1015','pede. Cum sociis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('445','Cras','justo.','938','sem magna');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('446','nulla.','non,','708','id, mollis nec, cursus a, enim. Suspendisse');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('447','Fusce','mollis','1027','Etiam laoreet, libero');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('448','nibh','felis','708','eu augue porttitor interdum. Sed auctor odio');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('449','risus','diam.','901','odio vel est');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('450','facilisi.','Etiam','937','ac mattis semper, dui lectus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('451','aliquet,','lacinia','872','ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('452','magna','erat','807','et ultrices posuere cubilia Curae; Phasellus ornare.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('453','interdum','non','809','a, scelerisque sed, sapien. Nunc pulvinar arcu et');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('454','tempor','gravida.','854','auctor non, feugiat nec, diam. Duis mi');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('455','accumsan','nisi','652','Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('456','eu','sem,','676','Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('457','posuere','quis,','654','sit');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('458','interdum','dolor','983','Integer sem elit, pharetra');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('459','libero','Duis','1023','lectus. Nullam suscipit, est ac facilisis');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('460','vitae,','dui','918','interdum');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('461','Donec','malesuada','769','dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('462','sed','accumsan','1006','mauris id sapien. Cras dolor dolor, tempus');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('463','purus.','ligula','793','Cum sociis natoque penatibus et magnis dis parturient');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('464','blandit','consectetuer','979','ipsum. Curabitur');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('465','tempus','Mauris','767','eget lacus. Mauris non dui nec');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('466','Lorem','ante','1074','at fringilla purus mauris a');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('467','venenatis','Vivamus','1112','semper rutrum. Fusce');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('468','eget,','gravida.','789','euismod in,');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('469','orci.','mi','1049','ante dictum mi, ac mattis velit justo nec ante.');
Insert into DUPALPE1.SKUPINA (IDSKUPINY,NAZEV,HESLOPROPRIDANI,IDVEDOUCIHO,POPIS) values ('470','lorem','Vestibulum','1086','diam luctus lobortis. Class');
