INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('massa rutrum','0','79','682','Nam nulla magna, malesuada');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('id enim.','0','52','606','commodo ipsum. Suspendisse');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('at, velit.','0','79','505','erat nonummy');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('purus. Maecenas','1','164','525','aliquet, metus');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('faucibus ut,','0','172','530','posuere,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('lobortis quam','0','80','638','sodales.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('ullamcorper. Duis','1','113','662','eu nulla at');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('pede. Cras','1','58','531','mauris blandit mattis. Cras eget');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Duis at','0','58','653','enim commodo');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('amet, faucibus','1','6','550','risus. Donec egestas. Aliquam nec');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('ornare lectus','0','38','627','luctus');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('blandit. Nam','1','48','573','mattis. Integer eu');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('in, hendrerit','0','143','662','orci, consectetuer euismod est');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('massa. Mauris','1','173','630','mauris sit amet');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('molestie orci','1','196','552','ut,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('massa. Suspendisse','0','61','608','Sed');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('scelerisque neque','0','22','509','a tortor. Nunc');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('commodo at,','0','17','610','tortor. Nunc commodo auctor velit.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('condimentum eget,','0','62','525','mauris');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Mauris nulla.','0','130','559','Pellentesque habitant morbi tristique');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('auctor non,','0','69','610','Sed eu nibh vulputate');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('nec urna','1','117','513','sed, facilisis vitae, orci.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('mattis. Integer','1','23','664','et');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('hendrerit. Donec','0','82','663','amet orci. Ut sagittis');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Donec consectetuer','1','168','545','rutrum eu,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Vivamus non','1','118','582','conubia nostra,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('sit amet,','0','161','605','dictum eleifend,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('at, iaculis','0','192','638','nec');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('mi fringilla','1','108','531','at sem molestie');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('mus. Donec','0','32','592','vehicula et, rutrum');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('rutrum magna.','1','32','610','Nunc');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('erat volutpat.','0','141','623','nec orci. Donec nibh.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('mollis non,','0','57','502','urna.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('elementum sem,','1','1','625','euismod');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('fames ac','1','137','493','consequat dolor');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('nisi. Cum','0','137','623','arcu vel quam dignissim pharetra.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('egestas. Aliquam','1','150','647','lorem, auctor');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('risus. Quisque','0','124','524','malesuada vel, venenatis');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Quisque fringilla','1','87','594','orci, adipiscing');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('accumsan sed,','0','28','635','Aliquam rutrum');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('scelerisque neque','1','118','596','dictum eleifend, nunc');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('risus quis','1','30','491','iaculis nec,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('erat. Vivamus','0','8','685','quis lectus. Nullam');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('pretium aliquet,','1','61','501','in aliquet lobortis,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('nec luctus','1','190','615','molestie in,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('feugiat. Lorem','0','197','603','sed dictum eleifend, nunc');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('adipiscing elit.','1','196','520','natoque penatibus et magnis dis');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('massa lobortis','0','113','634','gravida mauris');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('magnis dis','1','181','614','Maecenas iaculis aliquet diam. Sed');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Proin vel','0','176','545','semper.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('In ornare','0','49','582','varius et, euismod et,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('consequat, lectus','1','161','663','urna. Nunc quis arcu');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('pede, nonummy','0','200','641','Mauris ut');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('vel pede','1','32','616','Aliquam');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('dolor sit','1','108','663','justo. Proin non massa');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Ut nec','0','134','540','ornare lectus justo eu');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('a, enim.','1','186','676','arcu vel quam');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('bibendum fermentum','1','39','618','neque vitae semper');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('dolor dapibus','0','189','506','Cras pellentesque. Sed dictum. Proin');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('dictum cursus.','1','123','631','turpis. Nulla aliquet. Proin');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('natoque penatibus','1','133','685','neque');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('at auctor','0','8','534','eget');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('porttitor vulputate,','1','56','516','nunc interdum');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Sed eu','0','198','583','turpis egestas.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Nunc mauris','1','144','529','Duis elementum,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('interdum ligula','1','42','540','eu, ligula. Aenean euismod');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('neque venenatis','1','71','626','tempor');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('lorem lorem,','0','38','593','hendrerit');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('pharetra nibh.','1','181','545','eu');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('vitae odio','1','175','656','at sem molestie sodales. Mauris');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Quisque porttitor','1','156','591','Nullam nisl. Maecenas malesuada fringilla');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('tincidunt congue','0','59','505','Cras');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('at, nisi.','0','95','628','fermentum metus. Aenean sed pede');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Mauris molestie','0','76','528','magna. Duis dignissim');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('ornare sagittis','1','68','561','arcu. Morbi sit');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('vel nisl.','1','171','550','pede nec');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('massa lobortis','1','25','683','vehicula.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('malesuada augue','1','136','661','magna tellus');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('gravida molestie','1','163','668','eros nec tellus. Nunc');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('enim nec','0','185','648','Nam porttitor scelerisque neque.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('est, mollis','0','31','678','eleifend, nunc risus');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('aliquet, metus','0','87','635','mi');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('ullamcorper. Duis','1','18','625','Aliquam erat');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('ornare, libero','1','191','511','vel quam dignissim pharetra. Nam');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('sem eget','0','194','556','ante.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('In tincidunt','0','144','662','gravida');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('tellus. Nunc','1','59','635','massa. Suspendisse eleifend.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('diam eu','1','186','554','mi enim,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('orci, consectetuer','1','46','619','lobortis augue scelerisque mollis.');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('Mauris nulla.','0','68','557','consequat enim');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('dolor dapibus','0','128','616','in sodales elit erat vitae');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('risus. Duis','0','115','508','nisi. Aenean eget metus. In');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('tellus. Suspendisse','0','123','574','elit, a feugiat');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('scelerisque scelerisque','0','68','680','non leo. Vivamus nibh dolor,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('non, sollicitudin','0','193','561','condimentum eget, volutpat ornare,');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('dui, in','1','77','575','magnis');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('arcu. Vestibulum','1','116','646','magna');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('ultricies adipiscing,','1','157','588','montes, nascetur ridiculus mus. Proin');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('penatibus et','1','117','620','Donec tempor, est ac');
INSERT INTO udalosti (nazev,verejna,idVlastnikaSk,idVlastnikaUz,popis) VALUES ('amet nulla.','1','155','602','Maecenas');