INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Aliquam','522','at, velit. Cras lorem','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('libero','528','augue scelerisque mollis. Phasellus libero','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('gravida.','602','sed pede.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('rutrum','652','ac, fermentum vel,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('lectus','587','enim, gravida sit','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('et,','498','eget mollis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nec','662','fringilla, porttitor vulputate, posuere vulputate,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Curabitur','511','a, magna.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('id,','675','Vestibulum ante ipsum primis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('mollis','550','luctus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('suscipit,','492','ultrices iaculis odio. Nam','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ante','606','nulla. Cras eu','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ac','638','sem molestie','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sodales','503','et tristique pellentesque, tellus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ullamcorper','550','sociis natoque penatibus et','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('pede.','644','sapien. Aenean','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('tincidunt','634','sodales at,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('scelerisque','602','Cras sed leo.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Nulla','626','arcu. Vestibulum ante ipsum','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sed','627','torquent per conubia nostra, per','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Proin','533','iaculis nec, eleifend non,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Pellentesque','606','aliquam eros turpis non','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('lacus.','637','vitae, sodales at,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('quam','530','lorem, sit amet ultricies','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('dignissim','597','dui quis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nulla','672','Integer tincidunt aliquam','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('diam','655','Suspendisse ac metus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nec','601','vestibulum nec, euismod in, dolor.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('neque','685','sem ut cursus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('mauris','572','Sed eget lacus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('enim.','667','quis accumsan convallis, ante','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Sed','613','malesuada vel,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sit','650','tempor lorem, eget','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ut','528','pede','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('metus.','604','arcu','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Fusce','656','egestas','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ante','529','turpis egestas. Aliquam fringilla cursus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nunc','540','non justo.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('non,','507','et magnis dis parturient montes,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sagittis','577','nulla.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('tristique','577','ac tellus. Suspendisse sed dolor.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Donec','491','fermentum convallis ligula.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('eu','686','in lobortis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('euismod','672','a,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Mauris','520','cursus luctus, ipsum leo','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('magna.','615','eget','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('diam','508','velit dui, semper et,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Integer','681','enim nisl elementum','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('id','615','Duis volutpat nunc sit','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('dictum','640','rhoncus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('orci,','669','sociis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Nullam','670','et, eros. Proin ultrices.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Cras','550','erat, eget tincidunt dui','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ac','498','commodo ipsum. Suspendisse non','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('lorem,','603','non, cursus non, egestas','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('et','627','arcu. Aliquam','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('a,','644','luctus et','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('tristique','684','morbi','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('in','491','ante','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ultricies','650','Nunc laoreet lectus quis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('massa','645','Sed diam','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('eget,','545','dolor sit amet,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('consectetuer','516','sit','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('pellentesque','620','Donec egestas.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('risus.','682','viverra. Maecenas iaculis aliquet','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ultricies','523','adipiscing lacus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('adipiscing','628','consectetuer rhoncus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('arcu.','514','facilisis. Suspendisse','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Nunc','660','iaculis, lacus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('magna','508','nonummy ac, feugiat non, lobortis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Curabitur','520','faucibus. Morbi','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Lorem','612','risus. Nulla eget metus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('imperdiet','498','neque venenatis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Mauris','674','Curae; Donec tincidunt.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nulla.','575','Pellentesque habitant morbi tristique','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('eu','578','neque venenatis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ipsum','530','turpis egestas. Fusce','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('quam','657','In','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('at','492','Phasellus libero mauris, aliquam eu,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('eros','578','lacus. Quisque imperdiet,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('lectus,','571','Integer tincidunt aliquam arcu.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nulla.','669','amet diam eu dolor','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nec','679','dis parturient montes, nascetur','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Proin','629','odio tristique pharetra. Quisque ac','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Sed','502','commodo auctor velit.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Nam','685','quam dignissim pharetra.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Donec','514','semper et,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('convallis','534','consequat','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('penatibus','543','felis orci, adipiscing','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('porttitor','625','odio tristique pharetra. Quisque','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('turpis','510','vel','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Nulla','616','lacinia. Sed congue, elit','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('elit,','585','Lorem ipsum dolor','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nascetur','539','sodales','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('vehicula','583','ac mattis ornare, lectus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('lectus.','565','dui nec urna','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('erat,','547','ullamcorper, velit in aliquet lobortis,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('leo,','665','feugiat placerat velit.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nunc.','679','arcu','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('commodo','682','dolor. Fusce feugiat. Lorem ipsum','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('tincidunt,','587','Aliquam ultrices','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('enim.','623','tempus mauris erat eget','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('amet,','564','gravida','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('purus,','672','nulla. Cras eu tellus eu','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('tellus','542','nulla. In','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('arcu','620','interdum libero dui','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sit','569','nulla','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('turpis','627','vitae,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('orci.','658','sem, consequat nec, mollis vitae,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('laoreet','537','magna,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sollicitudin','581','vel lectus. Cum sociis natoque','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('gravida','625','sed, sapien. Nunc pulvinar arcu','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ornare','558','tellus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('eros','525','faucibus orci luctus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('convallis','645','et netus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nunc','637','parturient montes,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('mauris.','501','accumsan','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('augue.','573','non arcu. Vivamus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('mollis','605','tempor augue ac ipsum. Phasellus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('massa','640','imperdiet ornare.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('vulputate,','549','tempus risus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('eros','652','enim commodo hendrerit. Donec porttitor','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Suspendisse','594','commodo hendrerit. Donec','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Class','652','sociis natoque penatibus et magnis','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('dis','644','nibh. Donec est','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Ut','653','In nec orci. Donec','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Vestibulum','685','tellus. Suspendisse','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('justo.','648','diam','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Duis','674','nibh. Quisque nonummy ipsum non','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('vitae,','559','tempus eu,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('eget,','596','nulla vulputate dui, nec tempus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('libero','581','ridiculus mus. Proin','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('amet','637','tortor. Integer aliquam','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('at','598','vulputate,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Nunc','582','dis parturient montes, nascetur ridiculus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('eleifend,','623','semper tellus id nunc interdum','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('interdum.','493','vulputate dui, nec','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Donec','596','quis lectus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('tortor,','530','facilisis eget, ipsum. Donec sollicitudin','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('vitae,','516','cursus non, egestas a,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Sed','595','lorem, sit amet','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sed,','510','arcu. Sed et','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('aliquet','668','tellus lorem eu metus. In','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('et','672','metus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('lobortis.','617','turpis egestas. Fusce aliquet','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ante.','515','Nulla','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('fringilla.','576','metus urna convallis erat,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Phasellus','623','gravida sagittis.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('magna','603','lobortis quis, pede.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('lobortis','607','malesuada augue','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ac','619','magna.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Integer','590','a, aliquet vel, vulputate eu,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Nam','548','morbi tristique senectus et','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('blandit','583','non leo. Vivamus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('orci','494','aliquet odio.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('non','682','commodo ipsum. Suspendisse','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('dolor.','646','rhoncus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sagittis.','533','amet nulla. Donec non justo.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Fusce','626','lobortis, nisi nibh lacinia','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('suscipit,','577','Nulla','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sociis','572','et netus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('lorem,','581','ornare,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('enim.','677','non','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('magna.','554','arcu. Curabitur','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('nibh','590','varius. Nam porttitor scelerisque','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('blandit','683','dictum cursus. Nunc mauris','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('eget','652','risus varius orci,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('aliquet','647','lacus.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('mauris','584','orci luctus et ultrices','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('facilisis','548','mollis. Integer','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Nunc','643','ante. Maecenas','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Cras','510','nec','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Aenean','517','in','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Phasellus','624','sit amet','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('In','576','interdum','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('est','595','enim, gravida sit','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('in','651','Mauris vestibulum,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('dictum','663','arcu ac orci. Ut semper','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('feugiat','496','fermentum','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('parturient','685','et pede. Nunc sed','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('et','517','nunc sed','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('mattis','581','non, lobortis quis,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('at,','518','neque sed dictum eleifend,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ligula.','684','placerat velit. Quisque','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('sed,','590','dictum ultricies ligula. Nullam','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('metus.','533','vel sapien imperdiet ornare.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('urna','589','nonummy ac,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('justo','577','orci luctus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('risus','641','pulvinar arcu et','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('non','605','nulla','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('adipiscing,','679','tellus justo sit','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('molestie','542','velit justo nec ante.','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('non,','598','Nulla','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('scelerisque','623','rhoncus id, mollis nec, cursus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('Cum','568','ac','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('ligula.','676','Mauris','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('elit.','578','vitae sodales nisi','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('lobortis','622','ornare placerat,','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('tristique','617','risus','1');
INSERT INTO skupiny (nazev,idVedouciho,popis,verejna) VALUES ('montes,','635','sapien, cursus in, hendrerit','1');